/* 
    Developer : Salim Deraiya
    Date : 23-11-2018
    File Comment : Dynamic Load Function Component
*/

import React from "react";
import {
    OrganizationInfoDashboard,
    ApplicationDashboard,
    UserDashboard,
    AdminsDashboard,
    CustomersDashboard,
    GroupDashboard,
    RoleDashboard,
    LanguageDashboard,
    MembershipLevelDashboard,
    EmailProviderDashboard,
    SocialLoginDashboard,
    TwoFactorAuthDashboard,
    ReportDashboard,
    SettingDashboard,
    DomainsDashboard,
    OrganizationFormDashboard,
    TotalApplicationDashboard,
    ActiveApplicationDashboard,
    InactiveApplicationDashboard,
    AddDomainDashboard,
    AddApplicationDashboard,
    AddAdminDashboard,
    ListDomainDashboard,
    ListAdminDashboard,
    ListCustomerDashboard,
    ListUserDashboard,
    List2FAAuthDashboard,
    ListEmailProviderDashboard,
    ListGroupDashboard,
    ListLanguageDashboard,
    ListMembershipLevelDashboard,
    ListRoleDashboard,
    ListSocialLoginDashboard,
    ViewDomainDashboard,
    ViewUserDashboard,
    ViewCustomerDashboard,
    ViewAdminDashboard,
    View2FAAuthDashboard,
    ViewEmailProviderDashboard,
    ViewGroupDashboard,
    ViewLanguageDashboard,
    ViewMembershipLevelDashboard,
    ViewRoleDashboard,
    ViewSocialLoginDashboard,
    AddUserDashboard,
    KYCConfigurationDashboard,
    KYCDocumentDashboard,
    KYCLevelDashboard,
    UserKYCConfigurationDashboard,
    AddKYCDocumentTypeForm,
    EditKYCDocumentTypeForm,
    ListKYCDocumentType,
    HelpNSupoortDashboard,
    AddKYCConfiguration,
    EditKYCConfiguration,
    ListKYCConfiguration,
    ListKYCVerifyWdgt,
    PasswordPolicyConfigurationDashboard,
    AddPasswordPolicyConfig,
    ListPasswordPolicyConfig,
    IPProfilingDashboard,
    AllowIPRangeDashboard,
    ListIPRangeDashboard,
    EditPasswordPolicy,
    EditKYCVerifyWdgt,
    SocialTradingPolicyDashboard,
    LeaderProfileDashboard,
    FollowerProfileDashboard,
    ManageAccountDashboard,
    AffiliateManagementDashboard,
    UserManagementDashboard,
    RuleManagementDashboard,
    RoleManagementDashboard,
    UserPermissionGroups,
    RuleModuleDashboard,
    RuleSubModuleDashboard,
    RuleFieldsDashboard,
    RuleToolDashboard,
    AddEditRuleModule,
    AddEditRuleSubModule,
    AddEditRuleField,
    AddEditRuleTool,
    ListRuleModule,
    ListRuleSubModule,
    ListRuleField,
    ListRuleTool,
    AddEditPermissionGroup,
    ListPermissionGroup,
    AssignRole,
    ViewRoleDetails,
    AffiliateConfiguration,
    AffiliateCommissionPattern,
    ViewPermissionGroupDetails,
    AffiliateSchemeDashboard,
    AffiliateSchemeTypeDashboard,
    AffiliatePromotionDashboard,
    ListAffiliateScheme,
    ListAffiliateSchemeType,
    ListAffiliatePromotion,
    AddEditAffiliateScheme,
    AddEditAffiliateSchemeType,
    AddEditAffiliatePromotion,
    SetPermission,
    TwoFactoreAuthWdgtBlk,
    ProviderBalanceCheck,

    //Added By Kevin
    ProfileInformationDashboard,
    SecurityDashboard,
    PersonalInformationDashboard,
    EmailAddressDashboard,
    PhoneNumberDashboard,
    ChangePasswordDashboard,
    SecurityQuestionDashboard,
    IPWhitelistDashboard,
    TwoFactorAuthenticationDashboard,
    PreferencesDashboard,
    PrnGroupDashboard,
    ActivityDashboard,
    PrnMembershipLevelDashboard,
    AllowIPDashboard,
    ListIPWhitelistDashboard,
    ListDeviceWhitelistDashboard,
    LoginHistoryDashboard,
    IPHistoryDashboard,
    UpgradeMembershipDashboard,
    PrnSettingDashboard,
    AddCustomerDashboard,
    ListActiveDomainDashboard,
    ListInActiveDomainDashboard,
    ComplainReportDashboard,
    ComplainReplyDashboard,
    ListOpenComplainDashboard,
    ListCloseComplainDashboard,
    ListPendingComplainDashboard,
    UserSignupReportDashboard,
    ListUserSignupReportDashboard,
    ListActivityLogDashboard,
    SLAConfigurationDashboard,
    AddPriorityDashboard,
    AddSLAPriorityDashboard,
    ListSLAPriorityDashboard,
    EditSLAConfigurationDashboard,
    ProfileConfigDashboard,
    AddProfileConfigDashboard,
    ListProfileConfigDashboard,
    EditProfileConfigDashboard,

    //Added By Sanjay
    AppConfigurationDashboard,
    CreateApplication,
    ListApplications,
    UpdateAppConfig,
    ReferralSystemDashboard,
    ReferralRewardConfigDashboard,
    ReferralPayTypeDashboard,
    ListReferralPayType,
    AddReferralPayType,
    ReferralChannelTypeDashboard,
    ListReferralChannelType,
    AddReferralChannelType,
    ReferralServiceTypeDashboard,
    ListReferralServiceType,
    UpdateReferralServiceType,
    AddReferralServiceType,
    AddReferralRewardConfig,
    ListReferralRewardConfig,
    ListReferralInvite,
    UpdateReferralRewardConfig,
    ListInviteVieEmailAndSMS,
    ListSocialMediaInvite,
    ListReferralParticipate,
    ListReferralRewards,

    // Added By Bharat Jograna
    ReferralDashboard,
    SignupReport,
    BuyTradeReport,
    SellTradeReport,
    DepositeReport,
    // SendEmailsReport,
    // SendSMSReport,
    // ShareOnFacebookReport,
    ShareOnTwitterReport,
    ClickOnReferralLinkReport,
    UsersAndControl,
    RoleAssignHistory,
    AddEditRole,
    // ManageRoles,
    // ListUserRoleAssign,
    ListAffiliateFacebookShareReport,
    ListAffiliateTwitterShareReport,
    ListAffiliateClickOnLinkReport,
    UpdateAssignRole,
    ListUnassignUserRole,
    AssignRoleToUnassign,
    AffiliateSchemeTypeMappingDashboard,
    ListAffiliateSchemeTypeMapping,
    AddEditAffiliateSchemeTypeMapping,
    ReferralServiceDetailDashboard,
    ListReferralServiceDetail,
    AddEditReferralServiceDetail,

    //Added by Saloni
    AffiliateReportDashboard,
    ListAffiliateSignupReport,
    ListAffiliateCommissionReport,
    ListAffiliateEmailSentReport,
    ListAffiliateSmsSentReport,
    AddEditUser,
    ListUser,
    SocialTradingHistory,
    AffiliateSchemeDetailDashboard,
    ListAffiliateSchemeDetail,
    AddEditAffiliateSchemeDetail,
    ReferralSchemeTypeMappingDashboard,
    ListReferralSchemeTypeMapping,
    AddEditReferralSchemeTypeMapping,


} from 'Components/MyAccount/Dashboards';

import WalletList from "Components/Wallet/WalletList";
import TradingLedger from "Components/TradingWidgets/Reports/Components/trading-ledger";
//Added by salim dt:09/02/2019
import WithdrawalReport from "Components/Wallet/WithdrawalReport";
import DepositReport from "Components/Wallet/DepositReport";
import UserTradeReport from "Components/TradingWidgets/UserTrade/Components/UserTradeReport";
import LimitConfiguration from "Components/Wallet/LimitConfiguration/LimitConfiguration";

//Dynamic render drawer component...
const DynamicLoadComponent = ({ componentName, props, drawerClose, closeAll, pagedata, componentTlt, BreadCrumbData, state, menuDetail, TitleBit, manageAcc }) => {
    //Define Object of component...
    const components = {
        //Added by salim....
        OrganizationInfoDashboard: OrganizationInfoDashboard,
        ApplicationDashboard: ApplicationDashboard,
        UserDashboard: UserDashboard,
        AdminsDashboard: AdminsDashboard,
        CustomersDashboard: CustomersDashboard,
        GroupDashboard: GroupDashboard,
        RoleDashboard: RoleDashboard,
        LanguageDashboard: LanguageDashboard,
        MembershipLevelDashboard: MembershipLevelDashboard,
        EmailProviderDashboard: EmailProviderDashboard,
        SocialLoginDashboard: SocialLoginDashboard,
        TwoFactorAuthDashboard: TwoFactorAuthDashboard,
        ReportDashboard: ReportDashboard,
        SettingDashboard: SettingDashboard,
        DomainsDashboard: DomainsDashboard,
        OrganizationFormDashboard: OrganizationFormDashboard,
        TotalApplicationDashboard: TotalApplicationDashboard,
        ActiveApplicationDashboard: ActiveApplicationDashboard,
        InactiveApplicationDashboard: InactiveApplicationDashboard,
        AddDomainDashboard: AddDomainDashboard,
        AddApplicationDashboard: AddApplicationDashboard,
        AddAdminDashboard: AddAdminDashboard,
        ListDomainDashboard: ListDomainDashboard,
        ListAdminDashboard: ListAdminDashboard,
        ListCustomerDashboard: ListCustomerDashboard,
        ListUserDashboard: ListUserDashboard,
        List2FAAuthDashboard: List2FAAuthDashboard,
        ListEmailProviderDashboard: ListEmailProviderDashboard,
        ListGroupDashboard: ListGroupDashboard,
        ListLanguageDashboard: ListLanguageDashboard,
        ListMembershipLevelDashboard: ListMembershipLevelDashboard,
        ListRoleDashboard: ListRoleDashboard,
        ListSocialLoginDashboard: ListSocialLoginDashboard,
        ViewDomainDashboard: ViewDomainDashboard,
        ViewUserDashboard: ViewUserDashboard,
        ViewCustomerDashboard: ViewCustomerDashboard,
        ViewAdminDashboard: ViewAdminDashboard,
        View2FAAuthDashboard: View2FAAuthDashboard,
        ViewEmailProviderDashboard: ViewEmailProviderDashboard,
        ViewGroupDashboard: ViewGroupDashboard,
        ViewLanguageDashboard: ViewLanguageDashboard,
        ViewMembershipLevelDashboard: ViewMembershipLevelDashboard,
        ViewRoleDashboard: ViewRoleDashboard,
        ViewSocialLoginDashboard: ViewSocialLoginDashboard,
        AddUserDashboard: AddUserDashboard,
        KYCConfigurationDashboard: KYCConfigurationDashboard,
        KYCDocumentDashboard: KYCDocumentDashboard,
        KYCLevelDashboard: KYCLevelDashboard,
        UserKYCConfigurationDashboard: UserKYCConfigurationDashboard,
        AddKYCDocumentTypeForm: AddKYCDocumentTypeForm,
        EditKYCDocumentTypeForm: EditKYCDocumentTypeForm,
        ListKYCDocumentType: ListKYCDocumentType,
        HelpNSupoortDashboard: HelpNSupoortDashboard,
        AddKYCConfiguration: AddKYCConfiguration,
        EditKYCConfiguration: EditKYCConfiguration,
        ListKYCConfiguration: ListKYCConfiguration,
        ListKYCVerifyWdgt: ListKYCVerifyWdgt,
        PasswordPolicyConfigurationDashboard: PasswordPolicyConfigurationDashboard,
        AddPasswordPolicyConfig: AddPasswordPolicyConfig,
        ListPasswordPolicyConfig: ListPasswordPolicyConfig,
        IPProfilingDashboard: IPProfilingDashboard,
        AllowIPRangeDashboard: AllowIPRangeDashboard,
        ListIPRangeDashboard: ListIPRangeDashboard,
        EditPasswordPolicy: EditPasswordPolicy,
        EditKYCVerifyWdgt: EditKYCVerifyWdgt,
        SocialTradingPolicyDashboard: SocialTradingPolicyDashboard,
        LeaderProfileDashboard: LeaderProfileDashboard,
        FollowerProfileDashboard: FollowerProfileDashboard,
        ManageAccountDashboard: ManageAccountDashboard,
        UserTradeReport: UserTradeReport,
        LimitConfiguration: LimitConfiguration,
        AffiliateManagementDashboard: AffiliateManagementDashboard,
        UserManagementDashboard: UserManagementDashboard,
        RuleManagementDashboard: RuleManagementDashboard,
        RoleManagementDashboard: RoleManagementDashboard,
        UserPermissionGroups: UserPermissionGroups,
        RuleModuleDashboard: RuleModuleDashboard,
        RuleSubModuleDashboard: RuleSubModuleDashboard,
        RuleFieldsDashboard: RuleFieldsDashboard,
        RuleToolDashboard: RuleToolDashboard,
        AddEditRuleModule: AddEditRuleModule,
        AddEditRuleSubModule: AddEditRuleSubModule,
        AddEditRuleField: AddEditRuleField,
        AddEditRuleTool: AddEditRuleTool,
        ListRuleModule: ListRuleModule,
        ListRuleSubModule: ListRuleSubModule,
        ListRuleField: ListRuleField,
        ListRuleTool: ListRuleTool,
        AddEditPermissionGroup: AddEditPermissionGroup,
        ListPermissionGroup: ListPermissionGroup,
        AssignRole: AssignRole,
        ViewRoleDetails: ViewRoleDetails,
        AffiliateConfiguration: AffiliateConfiguration,
        AffiliateCommissionPattern: AffiliateCommissionPattern,
        ViewPermissionGroupDetails: ViewPermissionGroupDetails,
        AffiliateSchemeDashboard: AffiliateSchemeDashboard,
        AffiliateSchemeTypeDashboard: AffiliateSchemeTypeDashboard,
        AffiliatePromotionDashboard: AffiliatePromotionDashboard,
        ListAffiliateScheme: ListAffiliateScheme,
        ListAffiliateSchemeType: ListAffiliateSchemeType,
        ListAffiliatePromotion: ListAffiliatePromotion,
        AddEditAffiliateScheme: AddEditAffiliateScheme,
        AddEditAffiliateSchemeType: AddEditAffiliateSchemeType,
        AddEditAffiliatePromotion: AddEditAffiliatePromotion,
        SetPermission: SetPermission,
        TwoFactoreAuthWdgtBlk: TwoFactoreAuthWdgtBlk,
        ProviderBalanceCheck: ProviderBalanceCheck,
        //End by salim

        //Added By Kevin
        ProfileInformationDashboard: ProfileInformationDashboard,
        SecurityDashboard: SecurityDashboard,
        PersonalInformationDashboard: PersonalInformationDashboard,
        EmailAddressDashboard: EmailAddressDashboard,
        PhoneNumberDashboard: PhoneNumberDashboard,
        ChangePasswordDashboard: ChangePasswordDashboard,
        SecurityQuestionDashboard: SecurityQuestionDashboard,
        IPWhitelistDashboard: IPWhitelistDashboard,
        TwoFactorAuthenticationDashboard: TwoFactorAuthenticationDashboard,
        PreferencesDashboard: PreferencesDashboard,
        PrnGroupDashboard: PrnGroupDashboard,
        ActivityDashboard: ActivityDashboard,
        PrnMembershipLevelDashboard: PrnMembershipLevelDashboard,
        AllowIPDashboard: AllowIPDashboard,
        ListIPWhitelistDashboard: ListIPWhitelistDashboard,
        ListDeviceWhitelistDashboard: ListDeviceWhitelistDashboard,
        LoginHistoryDashboard: LoginHistoryDashboard,
        IPHistoryDashboard: IPHistoryDashboard,
        UpgradeMembershipDashboard: UpgradeMembershipDashboard,
        PrnSettingDashboard: PrnSettingDashboard,
        AddCustomerDashboard: AddCustomerDashboard,
        ListActiveDomainDashboard: ListActiveDomainDashboard,
        ListInActiveDomainDashboard: ListInActiveDomainDashboard,
        ComplainReportDashboard: ComplainReportDashboard,
        ComplainReplyDashboard: ComplainReplyDashboard,
        ListOpenComplainDashboard: ListOpenComplainDashboard,
        ListCloseComplainDashboard: ListCloseComplainDashboard,
        ListPendingComplainDashboard: ListPendingComplainDashboard,
        UserSignupReportDashboard: UserSignupReportDashboard,
        ListUserSignupReportDashboard: ListUserSignupReportDashboard,
        ListActivityLogDashboard: ListActivityLogDashboard,
        SLAConfigurationDashboard: SLAConfigurationDashboard,
        AddPriorityDashboard: AddPriorityDashboard,
        AddSLAPriorityDashboard: AddSLAPriorityDashboard,
        ListSLAPriorityDashboard: ListSLAPriorityDashboard,
        EditSLAConfigurationDashboard: EditSLAConfigurationDashboard,
        ProfileConfigDashboard: ProfileConfigDashboard,
        AddProfileConfigDashboard: AddProfileConfigDashboard,
        ListProfileConfigDashboard: ListProfileConfigDashboard,
        EditProfileConfigDashboard: EditProfileConfigDashboard,

        //Create By Sanjay
        AppConfigurationDashboard: AppConfigurationDashboard,
        CreateApplication: CreateApplication,
        ListApplications: ListApplications,
        UpdateAppConfig: UpdateAppConfig,
        WalletList: WalletList,
        WithdrawalReport: WithdrawalReport,
        DepositReport: DepositReport,
        TradingLedger: TradingLedger,
        ReferralSystemDashboard: ReferralSystemDashboard,
        ReferralRewardConfigDashboard: ReferralRewardConfigDashboard,
        ReferralPayTypeDashboard: ReferralPayTypeDashboard,
        ListReferralPayType: ListReferralPayType,
        AddReferralPayType: AddReferralPayType,
        ReferralChannelTypeDashboard: ReferralChannelTypeDashboard,
        ListReferralChannelType: ListReferralChannelType,
        AddReferralChannelType: AddReferralChannelType,
        ReferralServiceTypeDashboard: ReferralServiceTypeDashboard,
        ListReferralServiceType: ListReferralServiceType,
        UpdateReferralServiceType: UpdateReferralServiceType,
        AddReferralServiceType: AddReferralServiceType,
        AddReferralRewardConfig: AddReferralRewardConfig,
        ListReferralRewardConfig: ListReferralRewardConfig,
        ListReferralInvite: ListReferralInvite,
        UpdateReferralRewardConfig: UpdateReferralRewardConfig,
        ListInviteVieEmailAndSMS: ListInviteVieEmailAndSMS,
        ListSocialMediaInvite: ListSocialMediaInvite,
        ListReferralParticipate: ListReferralParticipate,
        ListReferralRewards: ListReferralRewards,

        // Added By Bharat Jograna
        ReferralDashboard: ReferralDashboard,
        SignupReport: SignupReport,
        BuyTradeReport: BuyTradeReport,
        SellTradeReport: SellTradeReport,
        DepositeReport: DepositeReport,
        // SendEmailsReport: SendEmailsReport,
        // SendSMSReport: SendSMSReport,
        // ShareOnFacebookReport: ShareOnFacebookReport,
        ShareOnTwitterReport: ShareOnTwitterReport,
        ClickOnReferralLinkReport: ClickOnReferralLinkReport,
        UsersAndControl: UsersAndControl,
        RoleAssignHistory: RoleAssignHistory,
        AddEditRole: AddEditRole,
        // ManageRoles: ManageRoles,
        // ListUserRoleAssign : ListUserRoleAssign,
        ListAffiliateFacebookShareReport: ListAffiliateFacebookShareReport,
        ListAffiliateTwitterShareReport: ListAffiliateTwitterShareReport,
        ListAffiliateClickOnLinkReport: ListAffiliateClickOnLinkReport,
        UpdateAssignRole: UpdateAssignRole,
        ListUnassignUserRole: ListUnassignUserRole,
        AssignRoleToUnassign: AssignRoleToUnassign,
        AffiliateSchemeTypeMappingDashboard: AffiliateSchemeTypeMappingDashboard,
        ListAffiliateSchemeTypeMapping: ListAffiliateSchemeTypeMapping,
        AddEditAffiliateSchemeTypeMapping: AddEditAffiliateSchemeTypeMapping,
        ReferralServiceDetailDashboard: ReferralServiceDetailDashboard,
        ListReferralServiceDetail: ListReferralServiceDetail,
        AddEditReferralServiceDetail: AddEditReferralServiceDetail,

        //Added by Saloni
        AffiliateReportDashboard: AffiliateReportDashboard,
        ListAffiliateSignupReport: ListAffiliateSignupReport,
        ListAffiliateCommissionReport: ListAffiliateCommissionReport,
        ListAffiliateEmailSentReport: ListAffiliateEmailSentReport,
        ListAffiliateSmsSentReport: ListAffiliateSmsSentReport,
        AddEditUser: AddEditUser,
        ListUser: ListUser,
        SocialTradingHistory: SocialTradingHistory,
        AffiliateSchemeDetailDashboard: AffiliateSchemeDetailDashboard,
        ListAffiliateSchemeDetail: ListAffiliateSchemeDetail,
        AddEditAffiliateSchemeDetail: AddEditAffiliateSchemeDetail,
        ReferralSchemeTypeMappingDashboard:ReferralSchemeTypeMappingDashboard,
        ListReferralSchemeTypeMapping:ListReferralSchemeTypeMapping,
        AddEditReferralSchemeTypeMapping:AddEditReferralSchemeTypeMapping,
    };

    return React.createElement(components[componentName], { props, drawerClose, closeAll, pagedata, componentTlt, BreadCrumbData, state, menuDetail, TitleBit, manageAcc });
}

export default DynamicLoadComponent;