//To store base currency
export const STORE_BASE_CURRENCY = 'STORE_BASE_CURRENCY';

//For Pair Listing, Method : GetTradePairAsset
export const FETCH_MARKET_LIST = 'FETCH_MARKET_LIST';
export const FETCH_MARKET_LIST_SUCCESS = 'FETCH_MARKET_LIST_SUCCESS';
export const FETCH_MARKET_LIST_FAILURE = 'FETCH_MARKET_LIST_FAILURE';
export const CLEAR_MARKET_LIST = 'CLEAR_MARKET_LIST';
export const REFRESH_MARKET_LIST = 'REFRESH_MARKET_LIST';

// For Margin Pair Listing
export const FETCH_MARGIN_MARKET_LIST_SUCCESS = 'FETCH_MARGIN_MARKET_LIST_SUCCESS';
export const FETCH_MARGIN_MARKET_LIST_FAILURE = 'FETCH_MARGIN_MARKET_LIST_FAILURE';

//For fetching market ticker
export const GET_MARKET_TICKER = 'GET_MARKET_TICKER';
export const GET_MARKET_TICKER_SUCCESS = 'GET_MARKET_TICKER_SUCCESS';
export const GET_MARKET_TICKER_FAILURE = 'GET_MARKET_TICKER_FAILURE';

//For fetching graph details
export const GET_GRAPH_DETAILS = 'GET_GRAPH_DETAILS';
export const GET_GRAPH_DETAILS_SUCCESS = 'GET_GRAPH_DETAILS_SUCCESS';
export const GET_GRAPH_DETAILS_FAILURE = 'GET_GRAPH_DETAILS_FAILURE';

//For fetching current price of selected currency
export const GET_PAIR_RATES = 'GET_PAIR_RATES';
export const GET_PAIR_RATES_SUCCESS = 'PAIR_RATE_SUCCESS';
export const GET_PAIR_RATES_FAILURE = 'PAIR_RATE_FAILURE';

// For getting balance of Wallet
export const GET_CURRENCY_BALANCE = 'GET_CURRENCY_BALANCE'
export const GET_CURRENCY_BALANCE_SUCCESS = 'GET_CURRENCY_BALANCE_SUCCESS'
export const GET_CURRENCY_BALANCE_FAILURE = 'GET_CURRENCY_BALANCE_FAILURE'

//To Buy or Sell Trades
export const BUY_SELL_TRADE = 'BUY_SELL_TRADE';
export const BUY_SELL_TRADE_SUCCESS = 'BUY_SELL_TRADE_SUCCESS';
export const BUY_SELL_TRADE_FAILURE = 'BUY_SELL_TRADE_FAILURE';
export const CLEAR_BUY_SELL_TRADE = 'CLEAR_BUY_SELL_TRADE';

//For Open Orders
export const FETCH_OPEN_ORDER_HISTORY = 'FETCH_OPEN_ORDER_HISTORY';
export const FETCH_OPEN_ORDER_SUCCESS = 'FETCH_OPEN_ORDER_SUCCESS';
export const FETCH_OPEN_ORDER_FAILURE = 'FETCH_OPEN_ORDER_FAILURE';
export const CLEAR_OPEN_ORDER = 'CLEAR_OPEN_ORDER';

// For Calcel Order
export const CANCEL_OPEN_ORDER = 'CANCEL_OPEN_ORDER'
export const CANCEL_OPEN_ORDER_SUCCESS = 'CANCEL_OPEN_ORDER_SUCCESS'
export const CANCEL_OPEN_ORDER_FAILURE = 'CANCEL_OPEN_ORDER_FAILURE'
export const CLEAR_CANCEL_OPEN_ORDER = 'CLEAR_CANCEL_OPEN_ORDER';

// For Recent Orders
export const FETCH_RECENT_ORDER = 'FETCH_RECENT_ORDER';
export const FETCH_RECENT_ORDER_SUCCESS = 'FETCH_RECENT_ORDER_SUCCESS';
export const FETCH_RECENT_ORDER_FAILURE = 'FETCH_RECENT_ORDER_FAILURE';
export const CLEAR_RECENT_ORDER = 'CLEAR_RECENT_ORDER';

//For Buyer Books
export const FETCH_BUYER_BOOK_LIST = 'FETCH_BUYER_BOOK_LIST';
export const FETCH_BUYER_BOOK_LIST_SUCCESS = 'FETCH_BUYER_BOOK_LIST_SUCCESS';
export const FETCH_BUYER_BOOK_LIST_FAILURE = 'FETCH_BUYER_BOOK_LIST_FAILURE';

//For Seller Books
export const FETCH_SELLER_BOOK_LIST = 'FETCH_SELLER_BOOK_LIST';
export const FETCH_SELLER_BOOK_LIST_SUCCESS = 'FETCH_SELLER_BOOK_LIST_SUCCESS';
export const FETCH_SELLER_BOOK_LIST_FAILURE = 'FETCH_SELLER_BOOK_LIST_FAILURE';

//For Global Market Trades
export const FETCH_MARKET_TRADE_LIST = 'FETCH_MARKET_TRADE_LIST';
export const FETCH_MARKET_TRADE_LIST_SUCCESS = 'FETCH_MARKET_TRADE_LIST_SUCCESS';
export const FETCH_MARKET_TRADE_LIST_FAILURE = 'FETCH_MARKET_TRADE_LIST_FAILURE';
export const CLEAR_MARKET_TRADE_LIST = 'CLEAR_MARKET_TRADE_LIST';

//For Getting Current Market Cap details of high-low vol, change per, etc,
export const FETCH_MARKET_CAP = 'FETCH_MARKET_CAP';
export const FETCH_MARKET_CAP_SUCCESS = 'FETCH_MARKET_CAP_SUCCESS';
export const FETCH_MARKET_CAP_FAILURE = 'FETCH_MARKET_CAP_FAILURE';

//To Get Order History
export const FETCH_ORDER_HISTORY = 'FETCH_ORDER_HISTORY';
export const FETCH_ORDER_HISTORY_SUCCESS = 'FETCH_ORDER_HISTORY_SUCCESS';
export const FETCH_ORDER_HISTORY_FAILURE = 'FETCH_ORDER_HISTORY_FAILURE';
export const CLEAR_ORDER_HISTORY = 'CLEAR_ORDER_HISTORY';

//For fetching favourites list
export const GET_FAVOURITES = 'GET_FAVOURITES';
export const GET_FAVOURITES_SUCCESS = 'GET_FAVOURITES_SUCCESS';
export const GET_MARGIN_FAVOURITES_SUCCESS = 'GET_MARGIN_FAVOURITES_SUCCESS';
export const GET_FAVOURITES_FAILURE = 'GET_FAVOURITES_FAILURE';
export const CLEAR_FAVOURITE = 'CLEAR_FAVOURITE';

//For adding favourite pair
export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const ADD_FAVOURITE_SUCCESS = 'ADD_FAVOURITE_SUCCESS';
export const ADD_FAVOURITE_FAILURE = 'ADD_FAVOURITE_FAILURE';

//For removing favourite pair
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';
export const REMOVE_FAVOURITE_SUCCESS = 'REMOVE_FAVOURITE_SUCCESS';
export const REMOVE_FAVOURITE_FAILURE = 'REMOVE_FAVOURITE_FAILURE';

//For List Wallet
export const GET_AD_WALLETS = 'GET_AD_WALLETS';
export const GET_AD_WALLETS_SUCCESS = 'GET_AD_WALLETS_SUCCESS';
export const GET_AD_WALLETS_FAILURE = 'GET_AD_WALLETS_FAILURE';

//For Generate Address
export const FetchGenerateAddress = 'FetchGenerateAddress'
export const GenerateAddressSuccess = 'GenerateAddressSuccess'
export const GenerateAddressFailure = 'GenerateAddressFailure'

//For Withdraw Request
export const FetchWithdrawRequest = 'FetchWithdrawRequest'
export const WithdrawRequestSuccess = 'WithdrawRequestSuccess'
export const WithdrawRequestFailure = 'WithdrawRequestFailure'

//For Feet and Limits of Withdraw
export const GET_FEEANDLIMIT = 'GET_FEEANDLIMIT';
export const GET_FEEANDLIMIT_SUCCESS = 'GET_FEEANDLIMIT_SUCCESS';
export const GET_FEEANDLIMIT_FAILURE = 'GET_FEEANDLIMIT_FAILURE';

//For Withdraw History
export const FETCHING_WITHFRAW_HISTORY_DATA = 'FETCHING_WITHFRAW_HISTORY_DATA'
export const FETCHING_WITHDRAW_HISTORY_DATA_SUCCESS = 'FETCHING_WITHDRAW_HISTORY_DATA_SUCCESS'
export const FETCHING_WITHDRAW_HISTORY_DATA_FAILURE = 'FETCHING_WITHDRAW_HISTORY_DATA_FAILURE'

//For Coin Change
export const CoinChange = 'CoinChange';
export const DropdownChange = 'DropdownChange';

//For Deposit History
export const FETCHING_DEPOSIT_HISTORY_DATA = 'FetchDepositHistory';
export const FETCH_DEPOSIT_HISTORY_SUCCESS = 'FetchDepositHistorySuccess';
export const FETCH_DEPOSIT_HISTORY_FAILURE = 'FetchDepositHistoryFailure';

//For Deposit
//get wallet Balance
export const GET_AD_BALANCE = 'GET_AD_BALANCE';
export const GET_AD_BALANCE_SUCCESS = 'GET_AD_BALANCE_SUCCESS';
export const GET_AD_BALANCE_FAILURE = 'GET_AD_BALANCE_FAILURE';

//get defualt wallet address
export const GET_DEFAULT_ADD = 'GET_DEFAULT_ADD';
export const GET_DEFAULT_ADD_SUCCESS = 'GET_DEFAULT_ADD_SUCCESS';
export const GET_DEFAULT_ADD_FAILURE = 'GET_DEFAULT_ADD_FAILURE';

//For Get balance
export const FETCH_BALANCE = 'FetchBalance'
export const FETCH_BALANCE_SUCCESS = 'FetchBalanceSuccess'
export const FETCH_BALANCE_FAILURE = 'FetchBalanceFailure'

//For Generate New Address
export const GENERATE_NEW_ADDRESS = 'GenerateNewAddress';
export const GENERATE_NEW_ADDRESS_SUCCESS = 'GenerateNewAddressSuccess'
export const GENERATE_NEW_ADDRESS_FAILURE = 'GenerateNewAddressFailure'

//for list coin
export const GET_COINLIST = 'GET_COINLIST'
export const GET_COINLIST_SUCCESS = 'GET_COINLIST_SUCCESS'
export const GET_COINLIST_FAILURE = 'GET_COINLIST_FAILURE'
export const GET_COINLIST_CLEAR = 'GET_COINLIST_CLEAR'

//For About US
export const ABOUTUS_FETCH_DATA = 'ABOUTUS_FETCH_DATA'
export const ABOUTUS_SUCCESS = 'ABOUTUS_SUCCESS'
export const ABOUTUS_FAILURE = 'ABOUTUS_FAILURE'

//For Contact Us
export const ADD_NEW_CONTACTUS = 'ADD_NEW_CONTACTUS'
export const ADD_CONTACTUS_SUCCESS = 'ADD_CONTACTUS_SUCCESS'
export const ADD_CONTACTUS_FAILURE = 'ADD_CONTACTUS_FAILURE'
export const CONTACTUS_CLEARDATA = 'CONTACTUS_CLEARDATA'


//For News Section
export const NEWSSECTION_FETCH = 'NEWSSECTION_FETCH'
export const NEWSSECTION_FETCH_SUCCESS = 'NEWSSECTION_FETCH_SUCCESS'
export const NEWSSECTION_FETCH_FAILURE = 'NEWSSECTION_FETCH_FAILURE'
export const CLEAR_NEWSSECTION_DATA = 'CLEAR_NEWSSECTION_DATA'

// for announcement section
export const ANNOUCEMENT_FETCH = 'ANNOUCEMENT_FETCH'
export const ANNOUCEMENT_FETCH_SUCCESS = 'ANNOUCEMENT_FETCH_SUCCESS'
export const ANNOUCEMENT_FETCH_FAILURE = 'ANNOUCEMENT_FETCH_FAILURE'
export const CLEAR_ANNOUNCEMENT_DATA = 'CLEAR_ANNOUNCEMENT_DATA'

//For FAQs
export const GET_FAQ = 'GET_FAQ';
export const GET_FAQ_SUCCESS = 'GET_FAQ_SUCCESS';
export const GET_FAQ_FAILURE = 'GET_FAQ_FAILURE';
export const GET_FAQ_CATEGORIES = 'GET_FAQ_CATEGORIES';
export const GET_FAQ_CATEGORIES_SUCCESS = 'GET_FAQ_CATEGORIES_SUCCESS';
export const GET_FAQ_CATEGORIES_FAILURE = 'GET_FAQ_CATEGORIES_FAILURE';
export const GET_FAQ_QUESTIONS = 'GET_FAQ_QUESTIONS';
export const GET_FAQ_QUESTIONS_SUCCESS = 'GET_FAQ_QUESTIONS_SUCCESS';
export const GET_FAQ_QUESTIONS_FAILURE = 'GET_FAQ_QUESTIONS_FAILURE';
export const UPDATE_SEARCH_FAQ = 'UPDATE_SEARCH_FAQ';
export const ON_SEARCH_FAQ = 'ON_SEARCH_FAQ';
export const SHOW_FAQ_LOADING_INDICATOR = 'SHOW_FAQ_LOADING_INDICATOR';

//for Fees and charges
export const FEESANDCHARGES_FETCH = 'FEESANDCHARGES_FETCH'
export const FEESANDCHARGES_SUCCESS = 'FEESANDCHARGES_SUCCESS'
export const FEESANDCHARGES_FAILURE = 'FEESANDCHARGES_FAILURE'

// for social login
export const SOCIAL_LOGIN = 'SOCIAL_LOGIN'
export const SOCIAL_LOGIN_SUCCESS = 'SOCIAL_LOGIN_SUCCESS'
export const SOCIAL_LOGIN_FAILURE = 'SOCIAL_LOGIN_FAILURE'

// For social facebook login
export const SOCIAL_FACEBOOK_LOGIN = 'SOCIAL_FACEBOOK_LOGIN'
export const SOCIAL_FACEBOOK_LOGIN_SUCCESS = 'SOCIAL_FACEBOOK_LOGIN_SUCCESS'
export const SOCIAL_FACEBOOK_LOGIN_FAILURE = 'SOCIAL_FACEBOOK_LOGIN_FAILURE'

//For Limit Control
export const FETCH_SAVE_LIMIT = 'FETCH_SAVE_LIMIT'
export const FETCH_SAVE_LIMIT_SUCCESS = 'FETCH_SAVE_LIMIT_SUCCESS'
export const FETCH_SAVE_LIMIT_FAILURE = 'FETCH_SAVE_LIMIT_FAILURE'

//For Fetch saved Limit Control
export const FETCH_LIMIT_CONTROL = 'FETCH_LIMIT_CONTROL'
export const FETCH_LIMIT_CONTROL_SUCCESS = 'FETCH_LIMIT_CONTROL_SUCCESS'
export const FETCH_LIMIT_CONTROL_FAILURE = 'FETCH_LIMIT_CONTROL_FAILURE'

// For Selected Slab in Token Stacking
export const FETCH_SELECTED_SLAB = 'FetchSelectedSlab'
export const FETCH_SELECTED_SLAB_SUCCESS = 'FetchSelectedSlabSuccess'
export const FETCH_SELECTED_SLAB_FAILURE = 'FetchSelectedSlabFailure'

// For Selected Slab in Token Stacking
export const FETCH_SLAB_LIST = 'FetchSlabList'
export const FETCH_SLAB_LIST_SUCCESS = 'FetchSlabListSuccess'
export const FETCH_SLAB_LIST_FAILURE = 'FetchSlabListFailure'

// For Token Staking Submit Button Click
export const ON_TOKEN_SUBMIT = 'OnTokenSubmit'
export const ON_TOKEN_SUBMIT_SUCCESS = 'OnTokenSubmitSuccess'
export const ON_TOKEN_SUBMIT_FAILURE = 'OnTokenSubmitFailure'

export const UNSTAKING_REQUEST = 'UNSTAKING_REQUEST'
export const UNSTAKING_REQUEST_SUCCESS = 'UNSTAKING_REQUEST_SUCCESS'
export const UNSTAKING_REQUEST_FAILURE = 'UNSTAKING_REQUEST_FAILURE'

//For Token Stacking History
export const FETCHING_TOKEN_STACKING_HISTORY_DATA = 'FetchTokenStackingHistory'
export const FETCHING_TOKEN_STACKING_HISTORY_SUCCESS = 'FetchTokenStackingSuccess'
export const FETCHING_TOKEN_STACKING_HISTORY_FAILURE = 'FetchTokenStackingFailure'

//for FORGOT PASSWORD
export const FORGOTPASSWORD_FETCH = 'FORGOTPASSWORD_FETCH'
export const FORGOTPASSWORD_SUCCESS = 'FORGOTPASSWORD_SUCCESS'
export const FORGOTPASSWORD_FAILURE = 'FORGOTPASSWORD_FAILURE'

//for verify email forgot password
export const VERIFYEMAIL_FETCH = 'VERIFYEMAIL_FETCH'
export const VERIFYEMAIL_SUCCESS = 'VERIFYEMAIL_SUCCESS'
export const VERIFYEMAIL_FAILURE = 'VERIFYEMAIL_FAILURE'

//For IP whitelist
export const FETCH_IP_WHITELIST = 'FETCH_WHITELIST_IP';
export const FETCH_IP_WHITELIST_SUCCESS = 'FETCH_WHITELIST_IP_SUCCESS';
export const FETCH_IP_WHITELIST_FAILURE = 'FETCH_WHITELIST_IP_FAILURE';

//For Adding IP Whitelist
export const FETCH_ADD_IP_WHITELIST = 'FETCH_ADD_WHITELIST_IP';
export const FETCH_ADD_IP_WHITELIST_SUCCESS = 'FETCH_ADD_WHITELIST_IP_SUCCESS';
export const FETCH_ADD_IP_WHITELIST_FAILURE = 'FETCH_ADD_WHITELIST_IP_FAILURE';

//For Login History
export const LOGIN_HISTORY_LIST = 'LOGIN_HISTORY_LIST'
export const LOGIN_HISTORY_LIST_SUCCESS = 'LOGIN_HISTORY_LIST_SUCCESS'
export const LOGIN_HISTORY_WIDGET_SUCCESS = 'LOGIN_HISTORY_WIDGET_SUCCESS'
export const LOGIN_HISTORY_LIST_FAILURE = 'LOGIN_HISTORY_LIST_FAILURE'

//for device whitelist
export const DEVICEHISTORY_FETCH = 'DEVICEHISTORY_FETCH';
export const DEVICEHISTORY_SUCCESS = 'DEVICEHISTORY_SUCCESS';
export const DEVICEHISTORY_FAILURE = 'DEVICEHISTORY_FAILURE';
export const CLEAR_DEVICE_WHITELIST_DATA = 'CLEAR_DEVICE_WHITELIST_DATA';

//for Complain
export const LIST_COMPLAIN = 'LIST_COMPLAIN';
export const LIST_COMPLAIN_SUCCESS = 'LIST_COMPLAIN_SUCCESS';
export const LIST_COMPLAIN_FAILURE = 'LIST_COMPLAIN_FAILURE';

export const ADD_COMPLAIN = 'ADD_COMPLAIN';
export const ADD_COMPLAIN_SUCCESS = 'ADD_COMPLAIN_SUCCESS';
export const ADD_COMPLAIN_FAILURE = 'ADD_COMPLAIN_FAILURE';

export const GET_COMPLAIN_BY_ID = 'GET_COMPLAIN_BY_ID';
export const GET_COMPLAIN_BY_ID_SUCCESS = 'GET_COMPLAIN_BY_ID_SUCCESS';
export const GET_COMPLAIN_BY_ID_FAILURE = 'GET_COMPLAIN_BY_ID_FAILURE';

export const REPLAY_COMPLAIN = 'REPLAY_COMPLAIN';
export const REPLAY_COMPLAIN_SUCCESS = 'REPLAY_COMPLAIN_SUCCESS';
export const REPLAY_COMPLAIN_FAILURE = 'REPLAY_COMPLAIN_FAILURE';

// For Complaint Type
export const GET_COMPLAIN_TYPE = 'GET_COMPLAIN_TYPE'
export const GET_COMPLAIN_TYPE_SUCCESS = 'GET_COMPLAIN_TYPE_SUCCESS'
export const GET_COMPLAIN_TYPE_FAILURE = 'GET_COMPLAIN_TYPE_FAILURE'

export const CLEAR_COMPLAIN_DATA = 'CLEAR_COMPLAIN_DATA'

//for reply Comlain
export const REPLAY_SEND = 'REPLAY_SEND';
export const REPLAY_SEND_SUCCESS = 'REPLAY_SEND_SUCCESS';
export const REPLAY_SEND_FAILURE = 'REPLAY_SEND_FAILURE';
export const REPLAY_SEND_CLEAR = 'REPLAY_SEND_CLEAR';
export const ADD_COMPLAIN_CLEAR = 'ADD_COMPLAIN_CLEAR';

//for new signup with email
export const EMAIL_SIGNUP = 'EMAIL_SIGNUP';
export const EMAIL_SIGNUP_SUCCESS = 'EMAIL_SIGNUP_SUCCESS';
export const EMAIL_SIGNUP_FAILURE = 'EMAIL_SIGNUP_FAILURE';

//For SignUp With OTP
export const VERIFY_SIGNUP_OTP = 'VerifySignUpOtp';
export const VERIFY_SIGNUP_OTP_SUCCESS = 'VerifySignUpOtpSuccess';
export const VERIFY_SIGNUP_OTP_FAILURE = 'VerifySignUpOtpFailure';

//For Membership levels 
export const GET_MEMBERSHIP_LEVEL = "GET_MEMBERSHIP_LEVEL";
export const GET_MEMBERSHIP_LEVEL_SUCCESS = "GET_MEMBERSHIP_LEVEL_SUCCESS";
export const GET_MEMBERSHIP_LEVEL_FAILURE = "GET_MEMBERSHIP_LEVEL_FAILURE";

//For Resend OTP
export const RESEND_OTP = 'ResendOtp';
export const RESEND_OTP_SUCCESS = 'ResendOtpSuccess';
export const RESEND_OTP_FAILURE = 'ResendOtpFailure';

//Normal Registration
export const NORMAL_REGISTER = 'NORMAL_REGISTER';
export const NORMAL_REGISTER_SUCCESS = 'NORMAL_REGISTER_SUCCESS';
export const NORMAL_REGISTER_FAILURE = 'NORMAL_REGISTER_FAILURE';

//Normal Login
export const NORMAL_LOGIN = 'NORMAL_LOGIN';
export const NORMAL_LOGIN_SUCCESS = 'NORMAL_LOGIN_SUCCESS';
export const NORMAL_LOGIN_FAILURE = 'NORMAL_LOGIN_FAILURE';

//for aboutus, privicy policy, refund policy
export const GET_PAGE_CONTENTS = 'GET_PAGE_CONTENTS'
export const GET_PAGE_CONTENTS_SUCCESS = 'GET_PAGE_CONTENTS_SUCCESS'
export const GET_PAGE_CONTENTS_FAILURE = 'GET_PAGE_CONTENTS_FAILURE'
export const CLEAR_PAGE_CONTENTS = 'CLEAR_PAGE_CONTENTS'

//For Change Password
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

// Edit Profile actions types 
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';

//For get profile
export const GET_PROFILE_BY_ID = 'GET_PROFILE_BY_ID';
export const GET_PROFILE_BY_ID_SUCCESS = 'GET_PROFILE_BY_ID_SUCCESS';
export const GET_PROFILE_BY_ID_FAILURE = 'GET_PROFILE_BY_ID_FAILURE';

//for clear reducer data
export const CLEAR_THINGS = 'CLEAR_THINGS';

//SignUp Mobile With OTP
export const SIGNUP_WITH_MOBILE = 'SIGNUP_WITH_MOBILE';
export const SIGNUP_WITH_MOBILE_SUCCESS = 'SIGNUP_WITH_MOBILE_SUCCESS';
export const SIGNUP_WITH_MOBILE_FAILURE = 'SIGNUP_WITH_MOBILE_FAILURE';
export const SIGNUP_WITH_MOBILE_EMAIL_CLEAR = 'SIGNUP_WITH_MOBILE_EMAIL_CLEAR';
export const SIGNUP_MOBILE_RESEND_OTP = 'SIGNUP_MOBILE_RESEND_OTP';
export const SIGNUP_MOBILE_RESEND_OTP_SUCCESS = 'SIGNUP_MOBILE_RESEND_OTP_SUCCESS';
export const SIGNUP_MOBILE_RESEND_OTP_FAILURE = 'SIGNUP_MOBILE_RESEND_OTP_FAILURE';
export const SIGNUP_MOBILE_VERIFY_OTP = 'SIGNUP_MOBILE_VERIFY_OTP';
export const SIGNUP_MOBILE_VERIFY_OTP_SUCCESS = 'SIGNUP_MOBILE_VERIFY_OTP_SUCCESS';
export const SIGNUP_MOBILE_VERIFY_OTP_FAILURE = 'SIGNUP_MOBILE_VERIFY_OTP_FAILURE';
export const REMOVE_LOGIN_DATA = 'REMOVE_LOGIN_DATA';
export const SIGNUP_RESEND_CONFIRM_EMAIL = 'SIGNUP_RESEND_CONFIRM_EMAIL';
export const SIGNUP_RESEND_CONFIRM_EMAIL_SUCCESS = 'SIGNUP_RESEND_CONFIRM_EMAIL_SUCCESS';
export const SIGNUP_RESEND_CONFIRM_EMAIL_FAILURE = 'SIGNUP_RESEND_CONFIRM_EMAIL_FAILURE';

//Forgot Password
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

//SignIn Email With OTP
export const SIGNIN_WITH_EMAIL = 'SIGNIN_WITH_EMAIL';
export const SIGNIN_WITH_EMAIL_SUCCESS = 'SIGNIN_WITH_EMAIL_SUCCESS';
export const SIGNIN_WITH_EMAIL_FAILURE = 'SIGNIN_WITH_EMAIL_FAILURE';
export const SIGNIN_EMAIL_RESEND_OTP = 'SIGNIN_EMAIL_RESEND_OTP';
export const SIGNIN_EMAIL_RESEND_OTP_SUCCESS = 'SIGNIN_EMAIL_RESEND_OTP_SUCCESS';
export const SIGNIN_EMAIL_RESEND_OTP_FAILURE = 'SIGNIN_EMAIL_RESEND_OTP_FAILURE';
export const SIGNIN_EMAIL_VERIFY_OTP = 'SIGNIN_EMAIL_VERIFY_OTP';
export const SIGNIN_EMAIL_VERIFY_OTP_SUCCESS = 'SIGNIN_EMAIL_VERIFY_OTP_SUCCESS';
export const SIGNIN_EMAIL_VERIFY_OTP_FAILURE = 'SIGNIN_EMAIL_VERIFY_OTP_FAILURE';

//SignIn Mobile With OTP
export const SIGNIN_WITH_MOBILE = 'SIGNIN_WITH_MOBILE';
export const SIGNIN_WITH_MOBILE_SUCCESS = 'SIGNIN_WITH_MOBILE_SUCCESS';
export const SIGNIN_WITH_MOBILE_FAILURE = 'SIGNIN_WITH_MOBILE_FAILURE';
export const SIGNIN_MOBILE_RESEND_OTP = 'SIGNIN_MOBILE_RESEND_OTP';
export const SIGNIN_MOBILE_RESEND_OTP_SUCCESS = 'SIGNIN_MOBILE_RESEND_OTP_SUCCESS';
export const SIGNIN_MOBILE_RESEND_OTP_FAILURE = 'SIGNIN_MOBILE_RESEND_OTP_FAILURE';
export const SIGNIN_MOBILE_VERIFY_OTP = 'SIGNIN_MOBILE_VERIFY_OTP';
export const SIGNIN_MOBILE_VERIFY_OTP_SUCCESS = 'SIGNIN_MOBILE_VERIFY_OTP_SUCCESS';
export const SIGNIN_MOBILE_VERIFY_OTP_FAILURE = 'SIGNIN_MOBILE_VERIFY_OTP_FAILURE';

//For Enable Google Auth
export const GET_GOOGLE_AUTH_INFO = "GET_GOOGLE_AUTH_INFO";
export const GET_GOOGLE_AUTH_INFO_SUCCESS = "GET_GOOGLE_AUTH_INFO_SUCCESS";
export const GET_GOOGLE_AUTH_INFO_FAILURE = "GET_GOOGLE_AUTH_INFO_FAILURE";
export const ENABLE_GOOGLE_AUTH = "ENABLE_GOOGLE_AUTH";
export const ENABLE_GOOGLE_AUTH_SUCCESS = "ENABLE_GOOGLE_AUTH_SUCCESS";
export const ENABLE_GOOGLE_AUTH_FAILURE = "ENABLE_GOOGLE_AUTH_FAILURE";

//For Disable Send Google Auth
export const DISABLE_GOOGLE_AUTH = "DISABLE_GOOGLE_AUTH";
export const DISABLE_GOOGLE_AUTH_SUCCESS = "DISABLE_GOOGLE_AUTH_SUCCESS";
export const DISABLE_GOOGLE_AUTH_FAILURE = "DISABLE_GOOGLE_AUTH_FAILURE";


//For 2FA Google Auth Verify
export const TWO_FA_GOOGLE_AUTHENTICATION = 'TWO_FA_GOOGLE_AUTHENTICATION';
export const TWO_FA_GOOGLE_AUTHENTICATION_SUCCESS = 'TWO_FA_GOOGLE_AUTHENTICATION_SUCCESS';
export const TWO_FA_GOOGLE_AUTHENTICATION_FAILURE = 'TWO_FA_GOOGLE_AUTHENTICATION_FAILURE';

//For Verify 2FA
export const VERIFY_2FA = 'VERIFY_2FA';
export const VERIFY_2FA_SUCCESS = 'VERIFY_2FA_SUCCESS';
export const VERIFY_2FA_FAILURE = 'VERIFY_2FA_FAILURE';

//For Verify 2FA For Withdraw Module
export const VERIFY_2FA_WITHDRAW = 'VERIFY_2FA_WITHDRAW';
export const VERIFY_2FA_WITHDRAW_SUCCESS = 'VERIFY_2FA_WITHDRAW_SUCCESS';
export const VERIFY_2FA_WITHDRAW_FAILURE = 'VERIFY_2FA_WITHDRAW_FAILURE';

//For Fund View module
// get all balances
export const GET_ALL_BALANCE = 'GET_ALL_BALANCE';
export const GET_ALL_BALANCE_SUCCESS = 'GET_ALL_BALANCE_SUCCESS';
export const GET_ALL_BALANCE_FAILURE = 'GET_ALL_BALANCE_FAILURE';

// get seprated balance
export const GET_WALLETBALANCE = 'GET_WALLETBALANCE';
export const GET_WALLETBALANCE_SUCCESS = 'GET_WALLETBALANCE_SUCCESS';
export const GET_WALLETBALANCE_FAILURE = 'GET_WALLETBALANCE_FAILURE';

//For Ip Whitelist
export const LIST_IP_WHITELIST = "LIST_IP_WHITELIST";
export const LIST_IP_WHITELIST_SUCCESS = "LIST_IP_WHITELIST_SUCCESS";
export const LIST_IP_WHITELIST_FAILURE = "LIST_IP_WHITELIST_FAILURE";


//For Add IP to WhiteList
export const ADD_IP_TO_WHITELIST = "ADD_IP_TO_WHITELIST";
export const ADD_IP_TO_WHITELIST_SUCCESS = "ADD_IP_TO_WHITELIST_SUCCESS";
export const ADD_IP_TO_WHITELIST_FAILURE = "ADD_IP_TO_WHITELIST_FAILURE";

//For Add IP to WhiteList
export const UPDATE_IP_TO_WHITELIST = "UPDATE_IP_TO_WHITELIST";
export const UPDATE_IP_TO_WHITELIST_SUCCESS = "UPDATE_IP_TO_WHITELIST_SUCCESS";
export const UPDATE_IP_TO_WHITELIST_FAILURE = "UPDATE_IP_TO_WHITELIST_FAILURE";

//For Delete IP to WhiteList
export const DELETE_IP_TO_WHITELIST = "DELETE_IP_TO_WHITELIST";
export const DELETE_IP_TO_WHITELIST_SUCCESS = "DELETE_IP_TO_WHITELIST_SUCCESS";
export const DELETE_IP_TO_WHITELIST_FAILURE = "DELETE_IP_TO_WHITELIST_FAILURE";

//For Disable IP to WhiteList
export const DISABLE_IP_TO_WHITELIST = "DISABLE_IP_TO_WHITELIST";
export const DISABLE_IP_TO_WHITELIST_SUCCESS = "DISABLE_IP_TO_WHITELIST_SUCCESS";
export const DISABLE_IP_TO_WHITELIST_FAILURE = "DISABLE_IP_TO_WHITELIST_FAILURE";

//For Enable IP to WhiteList
export const ENABLE_IP_TO_WHITELIST = "ENABLE_IP_TO_WHITELIST";
export const ENABLE_IP_TO_WHITELIST_SUCCESS = "ENABLE_IP_TO_WHITELIST_SUCCESS";
export const ENABLE_IP_TO_WHITELIST_FAILURE = "ENABLE_IP_TO_WHITELIST_FAILURE";

// For Clear IP Whitelist data
export const CLEAR_IP_WHITELIST = "CLEAR_IP_WHITELIST";

//For User Ledger 
export const USER_LEDGER_LIST = 'USER_LEDGER_LIST';
export const USER_LEDGER_LIST_SUCCESS = 'USER_LEDGER_LIST_SUCCESS';
export const USER_LEDGER_LIST_FAILURE = 'USER_LEDGER_LIST_FAILURE';

//For Wallet List
export const FETCH_WALLET_LIST = 'FETCH_WALLET_LIST';
export const FETCH_WALLET_LIST_SUCCESS = 'FETCH_WALLET_LIST_SUCCESS';
export const FETCH_WALLET_LIST_FAILURE = 'FETCH_WALLET_LIST_FAILURE';

// For GET GLOBAL PREFERENCE In Whitelist Address
export const GET_PREFERENCE = 'GET_PREFERENCE';
export const GET_PREFERENCE_SUCCESS = 'GET_PREFERENCE_SUCCESS';
export const GET_PREFERENCE_FAILURE = 'GET_PREFERENCE_FAILURE';

// For SET GLOBAL PREFERENCE In Whitelist Address
export const SET_PREFERENCE = 'SET_PREFERENCE';
export const SET_PREFERENCE_SUCCESS = 'SET_PREFERENCE_SUCCESS';
export const SET_PREFERENCE_FAILURE = 'SET_PREFERENCE_FAILURE';

// For Add Address To Whitdrawal Whitelist 
export const SUBMIT_WITHDRAWALADDRESSES = 'SUBMIT_WITHDRAWALADDRESSES';
export const SUBMIT_WITHDRAWALADDRESSES_SUCCESS = 'SUBMIT_WITHDRAWALADDRESSES_SUCCESS';
export const SUBMIT_WITHDRAWALADDRESSES_FAIL = 'SUBMIT_WITHDRAWALADDRESSES_FAIL';

// For Fetch Whitdrawal Whitelisted Address  
export const FETCH_WITHDRAWALADDRESS = 'FETCH_WITHDRAWALADDRESS';
export const FETCH_WITHDRAWALADDRESS_SUCCESS = 'FETCH_WITHDRAWALADDRESS_SUCCESS';
export const FETCH_WITHDRAWALADDRESS_FAIL = 'FETCH_WITHDRAWALADDRESS_FAIL';

// For Add To Address To Whitelisted Address  
export const ADDTO_WHITELIST = 'ADDTO_WHITELIST';
export const ADDTO_WHITELIST_SUCCESS = 'ADDTO_WHITELIST_SUCCESS';
export const ADDTO_WHITELIST_FAILURE = 'ADDTO_WHITELIST_FAILURE';

// For Remove Address From Whitelist  
export const REMOVE_WHITELIST = 'REMOVE_WHITELIST';
export const REMOVE_WHITELIST_SUCCESS = 'REMOVE_WHITELIST_SUCCESS';
export const REMOVE_WHITELIST_FAILURE = 'REMOVE_WHITELIST_FAILURE';

// For Delete Address From Whitelist  
export const DELETE_ADDRESSES = 'DELETE_ADDRESSES';
export const DELETE_ADDRESSES_SUCCESS = 'DELETE_ADDRESSES_SUCCESS';
export const DELETE_ADDRESSES_FAILURE = 'DELETE_ADDRESSES_FAILURE';

// For Transfer Out 
export const GET_OUTGOINGTRANSACTONS_REPORT = 'GET_OUTGOINGTRANSACTONS_REPORT';
export const GET_OUTGOINGTRANSACTONS_REPORT_SUCCESS = 'GET_OUTGOINGTRANSACTONS_REPORT_SUCCESS';
export const GET_OUTGOINGTRANSACTONS_REPORT_FAILURE = 'GET_OUTGOINGTRANSACTONS_REPORT_FAILURE';

//Normal Login
export const GENERATE_TOKEN = 'GENERATE_TOKEN';
export const GENERATE_TOKEN_SUCCESS = 'GENERATE_TOKEN_SUCCESS';
export const GENERATE_TOKEN_FAILURE = 'GENERATE_TOKEN_FAILURE';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILURE = 'REFRESH_TOKEN_FAILURE';
export const CHECK_TOKEN = 'CHECK_TOKEN';
export const CHECK_TOKEN_SUCCESS = 'CHECK_TOKEN_SUCCESS';
export const CHECK_TOKEN_FAILURE = 'CHECK_TOKEN_FAILURE';
export const CLEAR_GENERATE_TOKEN_DATA = 'CLEAR_GENERATE_TOKEN_DATA';

// for Transactionin history 02-11-2018
export const GET_INCOMINGTRANSACTONS_REPORT = 'GET_INCOMINGTRANSACTONS_REPORT';
export const GET_INCOMINGTRANSACTONS_REPORT_SUCCESS = 'GET_INCOMINGTRANSACTONS_REPORT_SUCCESS';
export const GET_INCOMINGTRANSACTONS_REPORT_FAILURE = 'GET_INCOMINGTRANSACTONS_REPORT_FAILURE';


// for backoffice_newsletter
export const GET_NEWSLETTER = "GET_NEWSLETTER";
export const GET_NEWSLETTER_SUCCESS = "GET_NEWSLETTER_SUCCESS";
export const GET_NEWSLETTER_FAILURE = "GET_NEWSLETTER_FAILURE";
export const ADD_NEWSLETTER = "ADD_NEWSLETTER";
export const ADD_NEWSLETTER_SUCCESS = "ADD_NEWSLETTER_SUCCESS";
export const ADD_NEWSLETTER_FAILURE = "ADD_NEWSLETTER_FAILURE";
export const EDIT_NEWSLETTER = "EDIT_NEWSLETTER";
export const EDIT_NEWSLETTER_SUCCESS = "EDIT_NEWSLETTER_SUCCESS";
export const EDIT_NEWSLETTER_FAILURE = "EDIT_NEWSLETTER_FAILURE";
export const CLEAR_NEWSLETTER = "CLEAR_NEWSLETTER";
export const CLEAR_NEWSLETTER_EDIT = "CLEAR_NEWSLETTER_EDIT";

// for backoffice ExchangeEarning screen
export const GET_EXCHANGEREPORT = "GET_EXCHANGEREPORT";
export const GET_EXCHANGEREPORT_SUCCESS = "GET_EXCHANGEREPORT_SUCCESS";
export const GET_EXCHANGEREPORT_FAILURE = "GET_EXCHANGEREPORT_FAILURE";

//for backoffice Country screen
export const GET_COUNTRY = "GET_COUNTRY";
export const GET_COUNTRY_SUCCESS = "GET_COUNTRY_SUCCESS";
export const GET_COUNTRY_FAILURE = "GET_COUNTRY_FAILURE";
export const ADD_COUNTRY = "ADD_COUNTRY";
export const ADD_COUNTRY_SUCCESS = "ADD_COUNTRY_SUCCESS";
export const ADD_COUNTRY_FAILURE = "ADD_COUNTRY_FAILURE";
export const CLEAR_COUNTRY = "CLEAR_COUNTRY";
export const EDIT_COUNTRY = "EDIT_COUNTRY";
export const EDIT_COUNTRY_SUCCESS = "EDIT_COUNTRY_SUCCESS";
export const EDIT_COUNTRY_FAILURE = "EDIT_COUNTRY_FAILURE";
export const CLEAR_COUNTRY_EDIT = "CLEAR_COUNTRY_EDIT";

//for backoffice Language screen
export const GET_LANGUAGE = "GET_LANGUAGE";
export const GET_LANGUAGE_SUCCESS = "GET_LANGUAGE_SUCCESS";
export const GET_LANGUAGE_FAILURE = "GET_LANGUAGE_FAILURE";
export const ADD_LANGUAGE = "ADD_COUNTRY";
export const ADD_LANGUAGE_SUCCESS = "ADD_COUNTRY_SUCCESS";
export const ADD_LANGUAGE_FAILURE = "ADD_COUNTRY_FAILURE";
export const CLEAR_LANGUAGE = "CLEAR_COUNTRY";
export const EDIT_LANGUAGE = "EDIT_COUNTRY";
export const EDIT_LANGUAGE_SUCCESS = "EDIT_COUNTRY_SUCCESS";
export const EDIT_LANGUAGE_FAILURE = "EDIT_COUNTRY_FAILURE";
export const CLEAR_LANGUAGE_EDIT = "CLEAR_COUNTRY_EDIT";

// for backoffice userapi screen
export const GET_USERAPI = "GET_USERAPI";
export const GET_USERAPI_SUCCESS = "GET_USERAPI_SUCCESS";
export const GET_USERAPI_FAILURE = "GET_USERAPI_FAILURE";
export const EDIT_USERAPI = "EDIT_USERAPI";
export const EDIT_USERAPI_SUCCESS = "EDIT_USERAPI_SUCCESS";
export const EDIT_USERAPI_FAILURE = "EDIT_USERAPI_FAILURE";
export const CLEAR_USERAPI_EDIT = "CLEAR_USERAPI_EDIT";

// for backoffice ReferralCommission screen 
export const GET_REFERRALCOMMISSION = "GET_REFERRALCOMMISSION";
export const GET_REFERRALCOMMISSION_SUCCESS = "GET_REFERRALCOMMISSION_SUCCESS";
export const GET_REFERRALCOMMISSION_FAILURE = "GET_REFERRALCOMMISSION_FAILURE";

//for ip history 
export const IP_HISTORY_LIST = "IP_HISTORY_LIST";
export const IP_HISTORY_LIST_SUCCESS = "IP_HISTORY_LIST_SUCCESS";
export const IP_HISTORY_LIST_FAILURE = "IP_HISTORY_LIST_FAILURE";

//For Prefrence
export const SAVE_OBJECT_PREFERENCE = 'SAVE_OBJECT_PREFERENCE';

// For setting cache
export const SET_CACHE = 'SET_CACHE';

//For subscribe notification
export const SUBSCRIBE_NOTIFICATION = 'SUBSCRIBE_NOTIFICATION';
export const SUBSCRIBE_NOTIFICATION_SUCCESS = 'SUBSCRIBE_NOTIFICATION_SUCCESS';
export const SUBSCRIBE_NOTIFICATION_FAILURE = 'SUBSCRIBE_NOTIFICATION_FAILURE';

//For unsubscribe notification
export const UNSUBSCRIBE_NOTIFICATION = 'UNSUBSCRIBE_NOTIFICATION';
export const UNSUBSCRIBE_NOTIFICATION_SUCCESS = 'UNSUBSCRIBE_NOTIFICATION_SUCCESS';
export const UNSUBSCRIBE_NOTIFICATION_FAILURE = 'UNSUBSCRIBE_NOTIFICATION_FAILURE';

//For clear subscribe, unsubscribe data
export const CLEAR_NOTIFICATION_DATA = 'CLEAR_NOTIFICATION_DATA';

export const ACTION_LOGOUT = 'ACTION_LOGOUT';

//For Personal KYC Module
export const PERSONAL_VERIFICATION = 'PERSONAL_VERIFICATION';
export const PERSONAL_VERIFICATION_SUCCESS = 'PERSONAL_VERIFICATION_SUCCESS';
export const PERSONAL_VERIFICATION_FAILURE = 'PERSONAL_VERIFICATION_FAILURE';

//For device white list 
export const DELETE_DEVICE_WHITELIST = 'DELETE_DEVICE_WHITELIST';
export const DELETE_DEVICE_WHITELIST_SUCCESS = 'DELETE_DEVICE_WHITELIST_SUCCESS';
export const DELETE_DEVICE_WHITELIST_FAILURE = 'DELETE_DEVICE_WHITELIST_FAILURE';

//For device white list 
export const DISABLE_DEVICE_WHITELIST = 'DISABLE_DEVICE_WHITELIST';
export const DISABLE_DEVICE_WHITELIST_SUCCESS = 'DISABLE_DEVICE_WHITELIST_SUCCESS';
export const DISABLE_DEVICE_WHITELIST_FAILURE = 'DISABLE_DEVICE_WHITELIST_FAILURE';

//For device white list 
export const ENABLE_DEVICE_WHITELIST = 'ENABLE_DEVICE_WHITELIST';
export const ENABLE_DEVICE_WHITELIST_SUCCESS = 'ENABLE_DEVICE_WHITELIST_SUCCESS';
export const ENABLE_DEVICE_WHITELIST_FAILURE = 'ENABLE_DEVICE_WHITELIST_FAILURE';

// Social Profile Module

//Get Social Profile Subscription 
export const GET_SOCIAL_PROFILE_SUBSCRIPTION = "GET_SOCIAL_PROFILE_SUBSCRIPTION";
export const GET_SOCIAL_PROFILE_SUBSCRIPTION_SUCCESS = "GET_SOCIAL_PROFILE_SUBSCRIPTION_SUCCESS";
export const GET_SOCIAL_PROFILE_SUBSCRIPTION_FAILURE = "GET_SOCIAL_PROFILE_SUBSCRIPTION_FAILURE";

//Social Profile Subscribe
export const SOCIAL_PROFILE_SUBSCRIBE = "SOCIAL_PROFILE_SUBSCRIBE";
export const SOCIAL_PROFILE_SUBSCRIBE_SUCCESS = "SOCIAL_PROFILE_SUBSCRIBE_SUCCESS";
export const SOCIAL_PROFILE_SUBSCRIBE_FAILURE = "SOCIAL_PROFILE_SUBSCRIBE_FAILURE";

//Social Profile UnSubscribe
export const SOCIAL_PROFILE_UNSUBSCRIBE = "SOCIAL_PROFILE_UNSUBSCRIBE";
export const SOCIAL_PROFILE_UNSUBSCRIBE_SUCCESS = "SOCIAL_PROFILE_UNSUBSCRIBE_SUCCESS";
export const SOCIAL_PROFILE_UNSUBSCRIBE_FAILURE = "SOCIAL_PROFILE_UNSUBSCRIBE_FAILURE";

//Add Leader Configuration
export const ADD_LEADER_CONFIG = "ADD_LEADER_CONFIG";
export const ADD_LEADER_CONFIG_SUCCESS = "ADD_LEADER_CONFIG_SUCCESS";
export const ADD_LEADER_CONFIG_FAILURE = "ADD_LEADER_CONFIG_FAILURE";

// for Group list 
export const GET_GROUP_LIST = 'GET_GROUP_LIST'
export const GET_GROUP_LIST_SUCCESS = 'GET_GROUP_LIST_SUCCESS'
export const GET_GROUP_LIST_FAILURE = 'GET_GROUP_LIST_FAILURE'

// for Add Watch
export const ADD_NEW_WATCH_LIST = 'ADD_NEW_WATCH_LIST'
export const ADD_NEW_WATCH_LIST_SUCCESS = 'ADD_NEW_WATCH_LIST_SUCCESS'
export const ADD_NEW_WATCH_LIST_FAILURE = 'ADD_NEW_WATCH_LIST_FAILURE'

// for Add to Watch List
export const ADD_TO_WATCH_LIST = 'ADD_TO_WATCH_LIST'
export const ADD_TO_WATCH_LIST_SUCCESS = 'ADD_TO_WATCH_LIST_SUCCESS'
export const ADD_TO_WATCH_LIST_FAILURE = 'ADD_TO_WATCH_LIST_FAILURE'

// for Remove item from watch list
export const REMOVE_FROM_WATCH_LIST = 'REMOVE_FROM_WATCH_LIST'
export const REMOVE_FROM_WATCH_LIST_SUCCESS = 'REMOVE_FROM_WATCH_LIST_SUCCESS'
export const REMOVE_FROM_WATCH_LIST_FAILURE = 'REMOVE_FROM_WATCH_LIST_FAILURE'

//Clear Leader Configuration Data
export const CLEAR_LEADER_CONFIG = 'CLEAR_LEADER_CONFIG'

//Follower Profile Configuration

//Get Leader list social profile
export const GET_LEADER_LIST = "GET_LEADER_LIST";
export const GET_LEADER_LIST_SUCCESS = "GET_LEADER_LIST_SUCCESS";
export const GET_LEADER_LIST_FAILURE = "GET_LEADER_LIST_FAILURE";

//Get Unfollow Leader social profile
export const UNFOLLOW_LEADER = "UNFOLLOW_LEADER";
export const UNFOLLOW_LEADER_SUCCESS = "UNFOLLOW_LEADER_SUCCESS";
export const UNFOLLOW_LEADER_FAILURE = "UNFOLLOW_LEADER_FAILURE";

//clear social profile
export const CLEAR_LEADER = "CLEAR_LEADER";

// Social Profile Top Gainer
export const GET_SOCIAL_PROFILE_TOP_GAINER_LIST = "GET_SOCIAL_PROFILE_TOP_GAINER_LIST";
export const GET_SOCIAL_PROFILE_TOP_GAINER_LIST_SUCCESS = "GET_SOCIAL_PROFILE_TOP_GAINER_LIST_SUCCESS";
export const GET_SOCIAL_PROFILE_TOP_GAINER_LIST_FAILURE = "GET_SOCIAL_PROFILE_TOP_GAINER_LIST_FAILURE";

// Social Profile Top Loser
export const GET_SOCIAL_PROFILE_TOP_LOSER_LIST = "GET_SOCIAL_PROFILE_TOP_LOSER_LIST";
export const GET_SOCIAL_PROFILE_TOP_LOSER_LIST_SUCCESS = "GET_SOCIAL_PROFILE_TOP_LOSER_LIST_SUCCESS";
export const GET_SOCIAL_PROFILE_TOP_LOSER_LIST_FAILURE = "GET_SOCIAL_PROFILE_TOP_LOSER_LIST_FAILURE";

// Social Profile Top Leader 
export const GET_SOCIAL_PROFILE_TOP_LEADER_LIST = "GET_SOCIAL_PROFILE_TOP_LEADER_LIST";
export const GET_SOCIAL_PROFILE_TOP_LEADER_LIST_SUCCESS = "GET_SOCIAL_PROFILE_TOP_LEADER_LIST_SUCCESS";
export const GET_SOCIAL_PROFILE_TOP_LEADER_LIST_FAILURE = "GET_SOCIAL_PROFILE_TOP_LEADER_LIST_FAILURE";

// for historical perfomance chart
export const GET_HISTORICAL_PERFORM_CHART = 'GET_HISTORICAL_PERFORM_CHART'
export const GET_HISTORICAL_PERFORM_CHART_SUCCESS = 'GET_HISTORICAL_PERFORM_CHART_SUCCESS'
export const GET_HISTORICAL_PERFORM_CHART_FAILURE = 'GET_HISTORICAL_PERFORM_CHART_FAILURE'

//Get Leader Portfolio List 
export const GET_LEADER_PORTFOLIO_LIST = "GET_LEADER_PORTFOLIO_LIST";
export const GET_LEADER_PORTFOLIO_LIST_SUCCESS = "GET_LEADER_PORTFOLIO_LIST_SUCCESS";
export const GET_LEADER_PORTFOLIO_LIST_FAILURE = "GET_LEADER_PORTFOLIO_LIST_FAILURE";

// Clear Follower Configuration Data
export const CLEAR_FOLLOWER_CONFIG_DATA = "CLEAR_FOLLOWER_CONFIG_DATA";

//Get Leader Follow By ID
export const GET_LEADER_FOLLOW_BY_ID = 'GET_LEADER_FOLLOW_BY_ID'
export const GET_LEADER_FOLLOW_BY_ID_SUCCESS = 'GET_LEADER_FOLLOW_BY_ID_SUCCESS'
export const GET_LEADER_FOLLOW_BY_ID_FAILURE = 'GET_LEADER_FOLLOW_BY_ID_FAILURE'

//Edit Follower Configuration
export const EDIT_FOLLOWER_CONFIG = 'EDIT_FOLLOWER_CONFIG'
export const EDIT_FOLLOWER_CONFIG_SUCCESS = 'EDIT_FOLLOWER_CONFIG_SUCCESS'
export const EDIT_FOLLOWER_CONFIG_FAILURE = 'EDIT_FOLLOWER_CONFIG_FAILURE'

//for Get/Set languages
export const GET_LANGUAGES = "GET_LANGUAGES";
export const GET_LANGUAGES_SUCCESS = "GET_LANGUAGES_SUCCESS";
export const GET_LANGUAGES_FAILURE = "GET_LANGUAGES_FAILURE";

export const SET_LANGUAGES = "SET_LANGUAGES";
export const SET_LANGUAGES_SUCCESS = "SET_LANGUAGES_SUCCESS";
export const SET_LANGUAGES_FAILURE = "SET_LANGUAGES_FAILURE";

//Top Gainer Records
export const GET_TOP_GAINERS_DATA = 'GET_TOP_GAINERS_DATA';
export const GET_TOP_GAINERS_DATA_SUCCESS = 'GET_TOP_GAINERS_DATA_SUCCESS';
export const GET_TOP_GAINERS_DATA_FAILURE = 'GET_TOP_GAINERS_DATA_FAILURE';

//Top Looser Records
export const GET_TOP_LOSERS_DATA = 'GET_TOP_LOSERS_DATA';
export const GET_TOP_LOSERS_DATA_SUCCESS = 'GET_TOP_LOSERS_DATA_SUCCESS';
export const GET_TOP_LOSERS_DATA_FAILURE = 'GET_TOP_LOSERS_DATA_FAILURE';

//Top Gainer Looser Records
export const GET_TOP_GAINERS_LOSERS_DATA = 'GET_TOP_GAINERS_LOSERS_DATA';
export const GET_TOP_GAINERS_LOSERS_DATA_SUCCESS = 'GET_TOP_GAINERS_LOSERS_DATA_SUCCESS';
export const GET_TOP_GAINERS_LOSERS_DATA_FAILURE = 'GET_TOP_GAINERS_LOSERS_DATA_FAILURE';
export const CLEAR_TOP_GAINERS_LOSERS_DATA = 'CLEAR_TOP_GAINERS_LOSERS_DATA';

//Market Depth Chart Records
export const GET_MARKET_DEPTH_DATA = 'GET_MARKET_DEPTH_DATA';
export const GET_MARKET_DEPTH_DATA_SUCCESS = 'GET_MARKET_DEPTH_DATA_SUCCESS';
export const GET_MARKET_DEPTH_DATA_FAILURE = 'GET_MARKET_DEPTH_DATA_FAILURE';
export const CLEAR_MARKET_DEPTH_DATA = 'CLEAR_MARKET_DEPTH_DATA';

// For Activity Log
export const GET_ACTIVITY_LOG_LIST = 'GET_ACTIVITY_LOG_LIST'
export const GET_ACTIVITY_LOG_LIST_SUCCESS = 'GET_ACTIVITY_LOG_LIST_SUCCESS'
export const GET_ACTIVITY_LOG_LIST_FAILURE = 'GET_ACTIVITY_LOG_LIST_FAILURE'

//For Get Module Type in Activity Log History
export const GET_MODULE_TYPE = "GET_MODULE_TYPE";
export const GET_MODULE_TYPE_SUCCESS = "GET_MODULE_TYPE_SUCCESS";
export const GET_MODULE_TYPE_FAILURE = "GET_MODULE_TYPE_FAILURE";

// For Trade Summary (Settled Order) History
export const GET_TRADE_SETTLED_DATA = 'GET_TRADE_SETTLED_DATA';
export const GET_TRADE_SETTLED_DATA_SUCCESS = 'GET_TRADE_SETTLED_DATA_SUCCESS';
export const GET_TRADE_SETTLED_DATA_FAILURE = 'GET_TRADE_SETTLED_DATA_FAILURE';
export const CLEAR_TRADE_SETTLED_DATA = 'CLEAR_TRADE_SETTLED_DATA';

//For pair list
export const GET_PAIR_LIST = 'GET_PAIR_LIST';
export const GET_PAIR_LIST_SUCCESS = 'GET_PAIR_LIST_SUCCESS';
export const GET_PAIR_LIST_FAILURE = 'GET_PAIR_LIST_FAILURE';
export const CLEAR_PAIR_LIST = 'CLEAR_PAIR_LIST';

//For Currency list
export const GET_CURRENCY_LIST = 'GET_CURRENCY_LIST';
export const GET_CURRENCY_LIST_SUCCESS = 'GET_CURRENCY_LIST_SUCCESS';
export const GET_CURRENCY_LIST_FAILURE = 'GET_CURRENCY_LIST_FAILURE';

//Organization LIST
export const ORGLIST = "ORGLIST";
export const ORGLIST_SUCCESS = "ORGLIST_SUCCESS";
export const ORGLIST_FAIL = "ORGLIST_FAIL";

//Get Wallet Type Master
export const GET_WALLET_TYPE_MASTER = 'GET_WALLET_TYPE_MASTER';
export const GET_WALLET_TYPE_MASTER_SUCCESS = 'GET_WALLET_TYPE_MASTER_SUCCESS';
export const GET_WALLET_TYPE_MASTER_FAILURE = 'GET_WALLET_TYPE_MASTER_FAILURE';

//Get Wallet Type
export const GET_WALLET_TYPE = 'GET_WALLET_TYPE';
export const GET_WALLET_TYPE_SUCCESS = 'GET_WALLET_TYPE_SUCCESS';
export const GET_WALLET_TYPE_FAILURE = 'GET_WALLET_TYPE_FAILURE';

//For Role Details
export const GET_ROLE_DETAILS = "GET_ROLE_DETAILS";
export const GET_ROLE_DETAILS_SUCCESS = "GET_ROLE_DETAILS_SUCCESS";
export const GET_ROLE_DETAILS_FAILURE = "GET_ROLE_DETAILS_FAILURE";

//For Wallet Transaction Type
export const GET_WALLET_TRANSACTION_TYPE = "GET_WALLET_TRANSACTION_TYPE";
export const GET_WALLET_TRANSACTION_TYPE_SUCCESS = "GET_WALLET_TRANSACTION_TYPE_SUCCESS";
export const GET_WALLET_TRANSACTION_TYPE_FAILURE = "GET_WALLET_TRANSACTION_TYPE_FAILURE";

//get pre confirmation details...
export const PRECONFIRMATIONDETAILS = 'PRECONFIRMATIONDETAILS';
export const PRECONFIRMATIONDETAILS_SUCCESS = 'PRECONFIRMATIONDETAILS_SUCCESS';
export const PRECONFIRMATIONDETAILS_FAILURE = 'PRECONFIRMATIONDETAILS_FAILURE';

//stak request
export const STAKREQUEST = 'STAKREQUEST';
export const STAKREQUEST_SUCCESS = 'STAKREQUEST_SUCCESS';
export const STAKREQUEST_FAILURE = 'STAKREQUEST_FAILURE';

// For List All Wallet 
export const LISTALLWALLETS = "LISTALLWALLETS";
export const LISTALLWALLETS_SUCCESS = "LISTALLWALLETS_SUCCESS";
export const LISTALLWALLETS_FAILURE = "LISTALLWALLETS_FAILURE";

// For List Wallet Users
export const LISTWALLETUSERS = "LISTWALLETUSERS";
export const LISTWALLETUSERS_SUCCESS = "LISTWALLETUSERS_SUCCESS";
export const LISTWALLETUSERS_FAILURE = "LISTWALLETUSERS_FAILURE";

// For Add Wallet User
export const ADDWALLETUSER = "ADDWALLETUSER";
export const ADDWALLETUSER_SUCCESS = "ADDWALLETUSER_SUCCESS";
export const ADDWALLETUSER_FAILURE = "ADDWALLETUSER_FAILURE";

// For Accept or Reject Wallet Request
export const ACCEPTREJECTWALLETREQUEST = "ACCEPTREJECTWALLETREQUEST";
export const ACCEPTREJECTWALLETREQUEST_SUCCESS = "ACCEPTREJECTWALLETREQUEST_SUCCESS";
export const ACCEPTREJECTWALLETREQUEST_FAILURE = "ACCEPTREJECTWALLETREQUEST_FAILURE";

// Clear Add User Data
export const CLEAR_ADD_USER_DATA = "CLEAR_ADD_USER_DATA";

// For List user Wallet Request
export const LIST_USER_WALLET_REQUEST = "LIST_USER_WALLET_REQUEST";
export const LIST_USER_WALLET_REQUEST_SUCCESS = "LIST_USER_WALLET_REQUEST_SUCCESS";
export const LIST_USER_WALLET_REQUEST_FAILURE = "LIST_USER_WALLET_REQUEST_FAILURE";

//for coin list request.
export const GET_COINLIST_REQUEST = "GET_COINLIST_REQUEST";
export const GET_COINLIST_REQUEST_SUCCESS = "GET_COINLIST_REQUEST_SUCCESS"
export const GET_COINLIST_REQUEST_FAILURE = "GET_COINLIST_REQUEST_FAILURE"
export const ADD_COINLIST_REQUEST = "ADD_COINLIST_REQUEST"
export const ADD_COINLIST_REQUEST_SUCCESS = "ADD_COINLIST_REQUEST_SUCCESS"
export const ADD_COINLIST_REQUEST_FAILURE = "ADD_COINLIST_REQUEST_FAILURE"
export const ADD_COINLIST_REQUEST_CLEAR = "ADD_COINLIST_REQUEST_CLEAR"

//social profile leader config
export const GET_LEADER_CONFIG = "GET_LEADER_CONFIG";
export const GET_LEADER_CONFIG_SUCCESS = "GET_LEADER_CONFIG_SUCCESS";
export const GET_LEADER_CONFIG_FAILURE = "GET_LEADER_CONFIG_FAILURE";

// For Resend Withdrawal Confirmation Mail
export const RESEND_WITHDRAWAL_EMAIL = "RESEND_WITHDRAWAL_EMAIL";
export const RESEND_WITHDRAWAL_EMAIL_SUCCESS = "RESEND_WITHDRAWAL_EMAIL_SUCCESS";
export const RESEND_WITHDRAWAL_EMAIL_FAILURE = "RESEND_WITHDRAWAL_EMAIL_FAILURE";

// for Front CMS Survey
export const GET_SURVEY = 'GET_SURVEY';
export const GET_SURVEY_SUCCESS = 'GET_SURVEY_SUCCESS';
export const GET_SURVEY_FAILURE = 'GET_SURVEY_FAILURE';

export const ADD_SURVEYRESULT = 'ADD_SURVEYRESULT';
export const ADD_SURVEYRESULT_SUCCESS = 'ADD_SURVEYRESULT_SUCCESS';
export const ADD_SURVEYRESULT_FAILURE = 'ADD_SURVEYRESULT_FAILURE';

export const GET_SURVEY_RESULTS_BY_ID = 'GET_SURVEY_RESULTS_BY_ID';
export const GET_SURVEY_RESULTS_BY_ID_SUCCESS = 'GET_SURVEY_RESULTS_BY_ID_SUCCESS';
export const GET_SURVEY_RESULTS_BY_ID_FAILURE = 'GET_SURVEY_RESULTS_BY_ID_FAILURE';
export const GET_SURVEY_RESULTS_BY_ID_CLEAR = 'GET_SURVEY_RESULTS_BY_ID_CLEAR';

// for Help Center module
export const GET_HELPMANUALMODUALS = 'GET_HELPMANUALMODUALS';
export const GET_HELPMANUALMODUALS_SUCCESS = 'GET_HELPMANUALMODUALS_SUCCESS';
export const GET_HELPMANUALMODUALS_FAILURE = 'GET_HELPMANUALMODUALS_FAILURE';

export const GET_HELPMANUALS_BY_ID = 'GET_HELPMANUALS_BY_ID';
export const GET_HELPMANUALS_BY_ID_SUCCESS = 'GET_HELPMANUALS_BY_ID_SUCCESS';
export const GET_HELPMANUALS_BY_ID_FAILURE = 'GET_HELPMANUALS_BY_ID_FAILURE';

//for social profile follower List
export const GET_FOLLOWER_LIST = "GET_FOLLOWER_LIST";
export const GET_FOLLOWER_LIST_SUCCESS = "GET_FOLLOWER_LIST_SUCCESS";
export const GET_FOLLOWER_LIST_FAILURE = "GET_FOLLOWER_LIST_FAILURE";

//for alliliate signup
export const AFFILIATE_SIGNUP = "AFFILIATE_SIGNUP";
export const AFFILIATE_SIGNUP_SUCCESS = "AFFILIATE_SIGNUP_SUCCESS";
export const AFFILIATE_SIGNUP_FAILURE = "AFFILIATE_SIGNUP_FAILURE";
export const AFFILIATE_CLEAR = "AFFILIATE_CLEAR";

//social Profile My watch List
export const GET_LEADER_WATCH_LIST = "GET_LEADER_WATCH_LIST";
export const GET_LEADER_WATCH_LIST_SUCCESS = "GET_LEADER_WATCH_LIST_SUCCESS";
export const GET_LEADER_WATCH_LIST_FAILURE = "GET_LEADER_WATCH_LIST_FAILURE";

//FOR Affiliate Dashboard 
export const GET_AFFILIATE_DATA = 'GET_AFFILIATE_DATA';
export const GET_AFFILIATE_DATA_SUCCESS = 'GET_AFFILIATE_DATA_SUCCESS';
export const GET_AFFILIATE_DATA_FAILURE = 'GET_AFFILIATE_DATA_FAILURE';

//For Site Token Module
export const GET_SITE_TOKEN = "GET_SITE_TOKEN";
export const GET_SITE_TOKEN_SUCCESS = "GET_SITE_TOKEN_SUCCESS";
export const GET_SITE_TOKEN_FAILURE = "GET_SITE_TOKEN_FAILURE";

export const GET_SITE_TOKEN_CALCULATION = "GET_SITE_TOKEN_CALCULATION";
export const GET_SITE_TOKEN_CALCULATION_SUCCESS = "GET_SITE_TOKEN_CALCULATION_SUCCESS";
export const GET_SITE_TOKEN_CALCULATION_FAILURE = "GET_SITE_TOKEN_CALCULATION_FAILURE";

export const SITE_TOKEN_CONVERSION = "SITE_TOKEN_CONVERSION";
export const SITE_TOKEN_CONVERSION_SUCCESS = "SITE_TOKEN_CONVERSION_SUCCESS";
export const SITE_TOKEN_CONVERSION_FAILURE = "SITE_TOKEN_CONVERSION_FAILURE";

//For Site token History
export const GET_SITE_TOKEN_REPORT_LIST = 'GET_SITE_TOKEN_REPORT_LIST';
export const GET_SITE_TOKEN_REPORT_LIST_SUCCESS = 'GET_SITE_TOKEN_REPORT_LIST_SUCCESS';
export const GET_SITE_TOKEN_REPORT_LIST_FAILURE = 'GET_SITE_TOKEN_REPORT_LIST_FAILURE';

//Get Leader Board List
export const GET_LEADER_BOARD_LIST = "GET_LEADER_BOARD_LIST";
export const GET_LEADER_BOARD_LIST_SUCCESS = "GET_LEADER_BOARD_LIST_SUCCESS";
export const GET_LEADER_BOARD_LIST_FAILURE = "GET_LEADER_BOARD_LIST_FAILURE";

//Get Affiliate Commission Pattern
export const GET_AFFILIATE_COMMISSION_PATTERN = "GET_AFFILIATE_COMMISSION_PATTERN";
export const GET_AFFILIATE_COMMISSION_PATTERN_SUCCESS = "GET_AFFILIATE_COMMISSION_PATTERN_SUCCESS";
export const GET_AFFILIATE_COMMISSION_PATTERN_FAILURE = "GET_AFFILIATE_COMMISSION_PATTERN_FAILURE";

// FOR AFFILIATE EMAIL SEND REPORT
export const GET_EMAIL_SEND_REPORT = "GET_EMAIL_SEND_REPORT";
export const GET_EMAIL_SEND_REPORT_SUCCESS = "GET_EMAIL_SEND_REPORT_SUCCESS";
export const GET_EMAIL_SEND_REPORT_FAILURE = "GET_EMAIL_SEND_REPORT_FAILURE";

//Referral Program actions.
export const GET_ENSTIMATED_COMMISSION = "GET_ENSTIMATED_COMMISSION";
export const GET_ENSTIMATED_COMMISSION_SUCCESS = "GET_ENSTIMATED_COMMISSION_SUCCESS";
export const GET_ENSTIMATED_COMMISSION_FAILURE = "GET_ENSTIMATED_COMMISSION_FAILURE";
export const GET_REFERRAL_CHANNEL_USER_COUNT = "GET_REFERRAL_CHANNEL_USER_COUNT";
export const GET_REFERRAL_CHANNEL_USER_COUNT_SUCCESS = "GET_REFERRAL_CHANNEL_USER_COUNT_SUCCESS";
export const GET_REFERRAL_CHANNEL_USER_COUNT_FAILURE = "GET_REFERRAL_CHANNEL_USER_COUNT_FAILURE";

// FOR AFFILIATE CLICK ON LINK REPORT
export const GET_CLICK_ON_LINK_REPORT = "GET_CLICK_ON_LINK_REPORT";
export const GET_CLICK_ON_LINK_REPORT_SUCCESS = "GET_CLICK_ON_LINK_REPORT_SUCCESS";
export const GET_CLICK_ON_LINK_REPORT_FAILURE = "GET_CLICK_ON_LINK_REPORT_FAILURE";

// FOR AFFILIATE COMMISSION REPORT
export const GET_COMMISSION_REPORT = "GET_COMMISSION_REPORT";
export const GET_COMMISSION_REPORT_SUCCESS = "GET_COMMISSION_REPORT_SUCCESS";
export const GET_COMMISSION_REPORT_FAILURE = "GET_COMMISSION_REPORT_FAILURE";

// FOR AFFILIATE SMS SEND REPORT
export const GET_SMS_SEND_REPORT = "GET_SMS_SEND_REPORT";
export const GET_SMS_SEND_REPORT_SUCCESS = "GET_SMS_SEND_REPORT_SUCCESS";
export const GET_SMS_SEND_REPORT_FAILURE = "GET_SMS_SEND_REPORT_FAILURE";

// FOR AFFILIATE FACEBOOK SHARE REPORT
export const GET_FACEBOOK_SHARE_REPORT = "GET_FACEBOOK_SHARE_REPORT";
export const GET_FACEBOOK_SHARE_REPORT_SUCCESS = "GET_FACEBOOK_SHARE_REPORT_SUCCESS";
export const GET_FACEBOOK_SHARE_REPORT_FAILURE = "GET_FACEBOOK_SHARE_REPORT_FAILURE";

// FOR AFFILIATE TWITTER SHARE REPORT
export const GET_TWITTER_SHARE_REPORT = "GET_TWITTER_SHARE_REPORT";
export const GET_TWITTER_SHARE_REPORT_SUCCESS = "GET_TWITTER_SHARE_REPORT_SUCCESS";
export const GET_TWITTER_SHARE_REPORT_FAILURE = "GET_TWITTER_SHARE_REPORT_FAILURE";

// FOR AFFILIATE SIGNUP REPORT
export const GET_AFFILIATE_SIGNUP_REPORT = "GET_AFFILIATE_SIGNUP_REPORT";
export const GET_AFFILIATE_SIGNUP_REPORT_SUCCESS = "GET_AFFILIATE_SIGNUP_REPORT_SUCCESS";
export const GET_AFFILIATE_SIGNUP_REPORT_FAILURE = "GET_AFFILIATE_SIGNUP_REPORT_FAILURE";

//For Get User Data
export const GET_USER_DATA = "GET_USER_DATA";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAILURE = "GET_USER_DATA_FAILURE";

//To Get Charge List to display Takers and Makers
export const GET_CHARGES_LIST = 'GET_CHARGES_LIST';
export const GET_CHARGES_LIST_SUCCESS = 'GET_CHARGES_LIST_SUCCESS';
export const GET_CHARGES_LIST_FAILURE = 'GET_CHARGES_LIST_FAILURE';

//For Get Provider List
export const GET_PROVIDER_LIST = "GET_PROVIDER_LIST";
export const GET_PROVIDER_LIST_SUCCESS = "GET_PROVIDER_LIST_SUCCESS";
export const GET_PROVIDER_LIST_FAILURE = "GET_PROVIDER_LIST_FAILURE";

// for Get Referral Service 
export const GET_REFERRAL_SERVICE = "GET_REFERRAL_SERVICE";
export const GET_REFERRAL_SERVICE_SUCCESS = "GET_REFERRAL_SERVICE_SUCCESS";
export const GET_REFERRAL_SERVICE_FAILURE = "GET_REFERRAL_SERVICE_FAILURE";

// for Get Referral PayType 
export const GET_REFERRAL_PAYTYPE = "GET_REFERRAL_PAYTYPE";
export const GET_REFERRAL_PAYTYPE_SUCCESS = "GET_REFERRAL_PAYTYPE_SUCCESS";
export const GET_REFERRAL_PAYTYPE_FAILURE = "GET_REFERRAL_PAYTYPE_FAILURE";

// FOR GET REFERRAL CHANNEL TYPE
export const GET_REFERRAL_CHANNEL_TYPE = "GET_REFERRAL_CHANNEL_TYPE";
export const GET_REFERRAL_CHANNEL_TYPE_SUCCESS = "GET_REFERRAL_CHANNEL_TYPE_SUCCESS";
export const GET_REFERRAL_CHANNEL_TYPE_FAILURE = "GET_REFERRAL_CHANNEL_TYPE_FAILURE";

// For Get Base Currency List 
export const GET_BASE_CURRENCY_LIST = "GET_BASE_CURRENCY_LIST";
export const GET_BASE_CURRENCY_LIST_SUCCESS = "GET_BASE_CURRENCY_LIST_SUCCESS";
export const GET_BASE_CURRENCY_LIST_FAILED = "GET_BASE_CURRENCY_LIST_FAILED";

// For Margin Trading 
export const LIST_MARGIN_WALLETS = "LIST_MARGIN_WALLETS";
export const LIST_MARGIN_WALLETS_SUCCESS = "LIST_MARGIN_WALLETS_SUCCESS";
export const LIST_MARGIN_WALLETS_FAILURE = "LIST_MARGIN_WALLETS_FAILURE";

export const GET_MARGIN_WALLET_LEDGER_DATA = "GET_MARGIN_WALLET_LEDGER_DATA";
export const GET_MARGIN_WALLET_LEDGER_DATA_SUCCESS = "GET_MARGIN_WALLET_LEDGER_DATA_SUCCESS";
export const GET_MARGIN_WALLET_LEDGER_DATA_FAILURE = "GET_MARGIN_WALLET_LEDGER_DATA_FAILURE";
export const GET_MARGIN_WALLET_LEDGER_DATA_CLEAR = "GET_MARGIN_WALLET_LEDGER_DATA_CLEAR";

//For Leverage Request Report
export const LEVERAGE_REQUEST_REPORT_LIST = 'LEVERAGE_REQUEST_REPORT_LIST';
export const LEVERAGE_REQUEST_REPORT_LIST_SUCCESS = 'LEVERAGE_REQUEST_REPORT_LIST_SUCCESS';
export const LEVERAGE_REQUEST_REPORT_LIST_FAILURE = 'LEVERAGE_REQUEST_REPORT_LIST_FAILURE';

// For Get Margin Wallet List 
export const GET_MARGIN_WALLET = "GET_MARGIN_WALLET";
export const GET_MARGIN_WALLET_SUCCESS = "GET_MARGIN_WALLET_SUCCESS";
export const GET_MARGIN_WALLET_FAILURE = "GET_MARGIN_WALLET_FAILURE";

// For Add Levearge Request 
export const ADD_LEVERAGE = "ADD_LEVERAGE";
export const ADD_LEVERAGE_SUCCESS = "ADD_LEVERAGE_SUCCESS";
export const ADD_LEVERAGE_FAILURE = "ADD_LEVERAGE_FAILURE";

// For Add Levarge Confirmation 
export const ADD_LEVERAGE_CONFIRMATION = "ADD_LEVERAGE_CONFIRMATION";
export const ADD_LEVERAGE_CONFIRMATION_SUCCESS = "ADD_LEVERAGE_CONFIRMATION_SUCCESS";
export const ADD_LEVERAGE_CONFIRMATION_FAILURE = "ADD_LEVERAGE_CONFIRMATION_FAILURE";

// Api Plan 
// For Api Plan list
export const GET_API_PLAN_LIST_DATA = "GET_API_PLAN_LIST_DATA";
export const GET_API_PLAN_LIST_DATA_SUCCESS = "GET_API_PLAN_LIST_DATA_SUCCESS";
export const GET_API_PLAN_LIST_DATA_FAILURE = "GET_API_PLAN_LIST_DATA_FAILURE";

// For Api Subscribe Plan
export const SUBSCRIBE_API_PLAN = "SUBSCRIBE_API_PLAN";
export const SUBSCRIBE_API_PLAN_SUCCESS = "SUBSCRIBE_API_PLAN_SUCCESS";
export const SUBSCRIBE_API_PLAN_FAILURE = "SUBSCRIBE_API_PLAN_FAILURE";

// For User Api Active Plan
export const GET_USER_ACTIVE_PLAN = 'GET_USER_ACTIVE_PLAN'
export const GET_USER_ACTIVE_PLAN_SUCCESS = 'GET_USER_ACTIVE_PLAN_SUCCESS'
export const GET_USER_ACTIVE_PLAN_FAILURE = 'GET_USER_ACTIVE_PLAN_FAILURE'

// For Manual Renew Api Plan
export const MANUAL_RENEW_API_PLAN = 'MANUAL_RENEW_API_PLAN'
export const MANUAL_RENEW_API_PLAN_SUCCESS = 'MANUAL_RENEW_API_PLAN_SUCCESS'
export const MANUAL_RENEW_API_PLAN_FAILURE = 'MANUAL_RENEW_API_PLAN_FAILURE'

// For Auto Renew Api Plan
export const SET_AUTO_RENEW_API_PLAN = 'SET_AUTO_RENEW_API_PLAN'
export const SET_AUTO_RENEW_API_PLAN_SUCCESS = 'SET_AUTO_RENEW_API_PLAN_SUCCESS'
export const SET_AUTO_RENEW_API_PLAN_FAILURE = 'SET_AUTO_RENEW_API_PLAN_FAILURE'

// For getting Auto Renew Api Plan
export const GET_AUTO_RENEW_API_PLAN = 'GET_AUTO_RENEW_API_PLAN'
export const GET_AUTO_RENEW_API_PLAN_SUCCESS = 'GET_AUTO_RENEW_API_PLAN_SUCCESS'
export const GET_AUTO_RENEW_API_PLAN_FAILURE = 'GET_AUTO_RENEW_API_PLAN_FAILURE'

// For Stop Auto Renew Api Plan
export const STOP_AUTO_RENEW_API_PLAN = 'STOP_AUTO_RENEW_API_PLAN'
export const STOP_AUTO_RENEW_API_PLAN_SUCCESS = 'STOP_AUTO_RENEW_API_PLAN_SUCCESS'
export const STOP_AUTO_RENEW_API_PLAN_FAILURE = 'STOP_AUTO_RENEW_API_PLAN_FAILURE'

// For Custom Limit Data
export const GET_CUSTOM_LIMITS = 'GET_CUSTOM_LIMITS'
export const GET_CUSTOM_LIMITS_SUCCESS = 'GET_CUSTOM_LIMITS_SUCCESS'
export const GET_CUSTOM_LIMITS_FAILURE = 'GET_CUSTOM_LIMITS_FAILURE'

// For Set User Api Custom Limit
export const SET_CUSTOM_LIMITS = 'SET_CUSTOM_LIMITS'
export const SET_CUSTOM_LIMITS_SUCCESS = 'SET_CUSTOM_LIMITS_SUCCESS'
export const SET_CUSTOM_LIMITS_FAILURE = 'SET_CUSTOM_LIMITS_FAILURE'

// For Edit Custom Limits
export const EDIT_CUSTOM_LIMITS = 'EDIT_CUSTOM_LIMITS'
export const EDIT_CUSTOM_LIMITS_SUCCESS = 'EDIT_CUSTOM_LIMITS_SUCCESS'
export const EDIT_CUSTOM_LIMITS_FAILURE = 'EDIT_CUSTOM_LIMITS_FAILURE'

// For Set Default Custom Limit
export const SET_DEFAULT_CUSTOM_LIMITS = 'SET_DEFAULT_CUSTOM_LIMITS'
export const SET_DEFAULT_CUSTOM_LIMITS_SUCCESS = 'SET_DEFAULT_CUSTOM_LIMITS_SUCCESS'
export const SET_DEFAULT_CUSTOM_LIMITS_FAILURE = 'SET_DEFAULT_CUSTOM_LIMITS_FAILURE'

// Clear Api Plan Data
export const CLEAR_API_PLAN_DATA = 'CLEAR_API_PLAN_DATA'

// Api Key
export const GET_API_KEY_LIST = "GET_API_KEY_LIST";
export const GET_API_KEY_LIST_SUCCESS = "GET_API_KEY_LIST_SUCCESS";
export const GET_API_KEY_LIST_FAILURE = "GET_API_KEY_LIST_FAILURE";

export const ADD_IP_ADDRESS = "ADD_IP_ADDRESS";
export const ADD_IP_ADDRESS_SUCCESS = "ADD_IP_ADDRESS_SUCCESS";
export const ADD_IP_ADDRESS_FAILURE = "ADD_IP_ADDRESS_FAILURE";

export const UPDATE_API_KEY_LIST = "UPDATE_API_KEY_LIST";
export const UPDATE_API_KEY_LIST_SUCCESS = "UPDATE_API_KEY_LIST_SUCCESS";
export const UPDATE_API_KEY_LIST_FAILURE = "UPDATE_API_KEY_LIST_FAILURE";

export const GENERATE_API_KEY = "GENERATE_API_KEY";
export const GENERATE_API_KEY_SUCCESS = "GENERATE_API_KEY_SUCCESS";
export const GENERATE_API_KEY_FAILURE = "GENERATE_API_KEY_FAILURE";

export const DELETE_API_KEY = "DELETE_API_KEY";
export const DELETE_API_KEY_SUCCESS = "DELETE_API_KEY_SUCCESS";
export const DELETE_API_KEY_FAILURE = "DELETE_API_KEY_FAILURE";

export const GET_IP_WHITELIST_DATA = "GET_IP_WHITELIST_DATA";
export const GET_IP_WHITELIST_DATA_SUCCESS = "GET_IP_WHITELIST_DATA_SUCCESS";
export const GET_IP_WHITELIST_DATA_FAILURE = "GET_IP_WHITELIST_DATA_FAILURE";

export const REMOVE_IP_ADDRESS = "REMOVE_IP_ADDRESS";
export const REMOVE_IP_ADDRESS_SUCCESS = "REMOVE_IP_ADDRESS_SUCCESS";
export const REMOVE_IP_ADDRESS_FAILURE = "REMOVE_IP_ADDRESS_FAILURE";

// for Referral System Plan Invites data 
export const GET_REFERRAL_INVITES_LIST = "GET_REFERRAL_INVITES_LIST";
export const GET_REFERRAL_INVITES_LIST_SUCCESS = "GET_REFERRAL_INVITES_LIST_SUCCESS";
export const GET_REFERRAL_INVITES_LIST_FAILURE = "GET_REFERRAL_INVITES_LIST_FAILURE";

// for Referral System Plan Email data 
export const GET_REFERRAL_EMAIL_LIST = "GET_REFERRAL_EMAIL_LIST";
export const GET_REFERRAL_EMAIL_LIST_SUCCESS = "GET_REFERRAL_EMAIL_LIST_SUCCESS";
export const GET_REFERRAL_EMAIL_LIST_FAILURE = "GET_REFERRAL_EMAIL_LIST_FAILURE";

// for Referral System Plan Email data 
export const GET_REFERRAL_PARTICIPANT_LIST = "GET_REFERRAL_PARTICIPANT_LIST";
export const GET_REFERRAL_PARTICIPANT_LIST_SUCCESS = "GET_REFERRAL_PARTICIPANT_LIST_SUCCESS";
export const GET_REFERRAL_PARTICIPANT_LIST_FAILURE = "GET_REFERRAL_PARTICIPANT_LIST_FAILURE";

// for Referral System Plan Click data 
export const GET_REFERRAL_CLICKS_LIST = "GET_REFERRAL_CLICKS_LIST";
export const GET_REFERRAL_CLICKS_LIST_SUCCESS = "GET_REFERRAL_CLICKS_LIST_SUCCESS";
export const GET_REFERRAL_CLICKS_LIST_FAILURE = "GET_REFERRAL_CLICKS_LIST_FAILURE";

// for Referral System Plan Convert data 
export const GET_REFERRAL_CONVERTS_LIST = "GET_REFERRAL_CONVERTS_LIST";
export const GET_REFERRAL_CONVERTS_LIST_SUCCESS = "GET_REFERRAL_CONVERTS_LIST_SUCCESS";
export const GET_REFERRAL_CONVERTS_LIST_FAILURE = "GET_REFERRAL_CONVERTS_LIST_FAILURE";

export const CLEAR_ALL_REFERRAL_DATA = "CLEAR_ALL_REFERRAL_DATA";

// for referral code ,url and description,send Email
export const GET_REFERRAL_URL = "GET_REFERRAL_URL";
export const GET_REFERRAL_URL_SUCCESS = "GET_REFERRAL_URL_SUCCESS";
export const GET_REFERRAL_URL_FAILURE = "GET_REFERRAL_URL_FAILURE";

export const GET_REFERRAL_SERVICE_DESCRIPTION = "GET_REFERRAL_SERVICE_DESCRIPTION";
export const GET_REFERRAL_SERVICE_DESCRIPTION_SUCCESS = "GET_REFERRAL_SERVICE_DESCRIPTION_SUCCESS";
export const GET_REFERRAL_SERVICE_DESCRIPTION_FAILURE = "GET_REFERRAL_SERVICE_DESCRIPTION_FAILURE";

export const GET_REFERRAL_CODE = "GET_REFERRAL_CODE";
export const GET_REFERRAL_CODE_SUCCESS = "GET_REFERRAL_CODE_SUCCESS";
export const GET_REFERRAL_CODE_FAILURE = "GET_REFERRAL_CODE_FAILURE";

export const REFERRAL_EMAIL_SEND = "REFERRAL_EMAIL_SEND";
export const REFERRAL_EMAIL_SEND_SUCCESS = "REFERRAL_EMAIL_SEND_SUCCESS";
export const REFERRAL_EMAIL_SEND_FAILURE = "REFERRAL_EMAIL_SEND_FAILURE";

export const REFERRAL_SMS_SEND = "REFERRAL_SMS_SEND";
export const REFERRAL_SMS_SEND_SUCCESS = "REFERRAL_SMS_SEND_SUCCESS";
export const REFERRAL_SMS_SEND_FAILURE = "REFERRAL_SMS_SEND_FAILURE";

export const CLEAR_SEND_DATA = "CLEAR_SEND_DATA";
export const CLEAR_REFERRAL_DATA = "CLEAR_REFERRAL_DATA";

export const VERIFY_2FA_API_KEY = "VERIFY_2FA_API_KEY";
export const VERIFY_2FA_API_KEY_SUCCESS = "VERIFY_2FA_API_KEY_SUCCESS";
export const VERIFY_2FA_API_KEY_FAILURE = "VERIFY_2FA_API_KEY_FAILURE";
export const CLEAR_API_KEY_DATA = "CLEAR_API_KEY_DATA";

export const CLEAR_DELETE_API_KEY_DATA = "CLEAR_DELETE_API_KEY_DATA";

//for Affiliate User
export const GET_AFFILIATE_USER_LIST = "GET_AFFILIATE_USER_LIST";
export const GET_AFFILIATE_USER_LIST_SUCCESS = "GET_AFFILIATE_USER_LIST_SUCCESS";
export const GET_AFFILIATE_USER_LIST_FAILURE = "GET_AFFILIATE_USER_LIST_FAILURE";
export const CLEAR_AFFILIATE_DATA = "CLEAR_AFFILIATE_DATA";

//For New Life Cycle Added Action Type For All Reducer
export const FUNDS_VIEW_CLEAR = 'FUNDS_VIEW_CLEAR';
export const COIN_SELECT_CLEAR = 'COIN_SELECT_CLEAR';

//to get view api key 
export const GET_API_KEY_BY_ID = 'GET_API_KEY_BY_ID';
export const GET_API_KEY_BY_ID_SUCCESS = 'GET_API_KEY_BY_ID_SUCCESS';
export const GET_API_KEY_BY_ID_FAILURE = 'GET_API_KEY_BY_ID_FAILURE';

//for list charges typewise
export const GET_WALLET_TYPE_CHARGES_LIST = "GET_WALLET_TYPE_CHARGES_LIST";
export const GET_WALLET_TYPE_CHARGES_LIST_SUCCESS = "GET_WALLET_TYPE_CHARGES_LIST_SUCCESS";
export const GET_WALLET_TYPE_CHARGES_LIST_FAILURE = "GET_WALLET_TYPE_CHARGES_LIST_FAILURE";

export const CLEAR_WALLET_TYPE_CHARGES_LIST = "CLEAR_WALLET_TYPE_CHARGES_LIST";

//commission Report 
export const GET_SCHEME_MAPPING_IDS = "GET_SCHEME_MAPPING_IDS";
export const GET_SCHEME_MAPPING_IDS_SUCCESS = "GET_SCHEME_MAPPING_IDS_SUCCESS";
export const GET_SCHEME_MAPPING_IDS_FAILURE = "GET_SCHEME_MAPPING_IDS_FAILURE";

//For Add Currency Logo
export const ADD_CURRENCY_LOGO = "ADD_CURRENCY_LOGO";
export const ADD_CURRENCY_LOGO_SUCCESS = "ADD_CURRENCY_LOGO_SUCCESS";
export const ADD_CURRENCY_LOGO_FAILURE = "ADD_CURRENCY_LOGO_FAILURE";

// unstak pre confirmation
export const UNSTAKPRECONFIRMATION = "UNSTAKPRECONFIRMATION";
export const UNSTAKPRECONFIRMATION_SUCCESS = "UNSTAKPRECONFIRMATION_SUCCESS";
export const UNSTAKPRECONFIRMATION_FAILURE = "UNSTAKPRECONFIRMATION_FAILURE";

// for affiliate Invite friend links
export const GET_AFFILIATE_INVITE_LINK = "GET_AFFILIATE_INVITE_LINK";
export const GET_AFFILIATE_INVITE_LINK_SUCCESS = "GET_AFFILIATE_INVITE_LINK_SUCCESS";
export const GET_AFFILIATE_INVITE_LINK_FAILURE = "GET_AFFILIATE_INVITE_LINK_FAILURE";

// for affiliate invite friends via Email
export const AFFILIATE_INVITE_BY_EMAIL = "AFFILIATE_INVITE_BY_EMAIL";
export const AFFILIATE_INVITE_BY_EMAIL_SUCCESS = "AFFILIATE_INVITE_BY_EMAIL_SUCCESS";
export const AFFILIATE_INVITE_BY_EMAIL_FAILURE = "AFFILIATE_INVITE_BY_EMAIL_FAILURE";

// for affiliate invite friends via SMS
export const AFFILIATE_INVITE_BY_SMS = "AFFILIATE_INVITE_BY_SMS";
export const AFFILIATE_INVITE_BY_SMS_SUCCESS = "AFFILIATE_INVITE_BY_SMS_SUCCESS";
export const AFFILIATE_INVITE_BY_SMS_FAILURE = "AFFILIATE_INVITE_BY_SMS_FAILURE";

export const CLEAR_AFFILIATE_INVITE_DATA = "CLEAR_AFFILIATE_INVITE_DATA";

// For Leverage Base Currency
export const LEVERAGE_BASE_CURRENCY = "LEVERAGE_BASE_CURRENCY";
export const LEVERAGE_BASE_CURRENCY_SUCCESS = "LEVERAGE_BASE_CURRENCY_SUCCESS";
export const LEVERAGE_BASE_CURRENCY_FAILURE = "LEVERAGE_BASE_CURRENCY_FAILURE";

// for Affiliate pie chart data
export const GET_AFFILIATE_PIE_CHART_DATA = "GET_AFFILIATE_PIE_CHART_DATA";
export const GET_AFFILIATE_PIE_CHART_DATA_SUCCESS = "GET_AFFILIATE_PIE_CHART_DATA_SUCCESS";
export const GET_AFFILIATE_PIE_CHART_DATA_FAILURE = "GET_AFFILIATE_PIE_CHART_DATA_FAILURE";

// for Affiliate line chart data
export const GET_AFFILIATE_LINE_CHART_DATA = "GET_AFFILIATE_LINE_CHART_DATA";
export const GET_AFFILIATE_LINE_CHART_DATA_SUCCESS = "GET_AFFILIATE_LINE_CHART_DATA_SUCCESS";
export const GET_AFFILIATE_LINE_CHART_DATA_FAILURE = "GET_AFFILIATE_LINE_CHART_DATA_FAILURE";

// for Margin Profit Loss Data
export const GET_MARGIN_PROFIT_LOSS_DATA = "GET_MARGIN_PROFIT_LOSS_DATA";
export const GET_MARGIN_PROFIT_LOSS_DATA_SUCCESS = "GET_MARGIN_PROFIT_LOSS_DATA_SUCCESS";
export const GET_MARGIN_PROFIT_LOSS_DATA_FAILURE = "GET_MARGIN_PROFIT_LOSS_DATA_FAILURE";

// for Open Position Report Data
export const GET_OPEN_POSITION_REPORT_DATA = "GET_OPEN_POSITION_REPORT_DATA";
export const GET_OPEN_POSITION_REPORT_DATA_SUCCESS = "GET_OPEN_POSITION_REPORT_DATA_SUCCESS";
export const GET_OPEN_POSITION_REPORT_DATA_FAILURE = "GET_OPEN_POSITION_REPORT_DATA_FAILURE";

//For Deleverage Pre Confirm
export const DELEVERAGE_PRE_CONFIRM = "DELEVERAGE_PRE_CONFIRM";
export const DELEVERAGE_PRE_CONFIRM_SUCCESS = "DELEVERAGE_PRE_CONFIRM_SUCCESS";
export const DELEVERAGE_PRE_CONFIRM_FAILURE = "DELEVERAGE_PRE_CONFIRM_FAILURE";

//For Deleverage Confirm
export const DELEVERAGE_CONFIRM = "DELEVERAGE_CONFIRM";
export const DELEVERAGE_CONFIRM_SUCCESS = "DELEVERAGE_CONFIRM_SUCCESS";
export const DELEVERAGE_CONFIRM_FAILURE = "DELEVERAGE_CONFIRM_FAILURE";

//To clear Margin Wallet List Reducer
export const CLEAR_MARGIN_WALLET = "CLEAR_MARGIN_WALLET";

//To clear Login History
export const CLEAR_LOGIN_HISTORY = "CLEAR_LOGIN_HISTORY";
